num: 6
seed: 0xd42b
Buck: Heheh!\nCheck this out, \v0103\x0001!\rThis is the Magma Stone, the treasure\nof Stark Mountain!\rSince I found it, that makes me the\ngreatest Trainer out of everyone!\rThanks, you all helped it happen!\r
Buck: Oof!\r
Buck: Whoa! Wow!\rHehehe! That was wicked!\nThe volcano's in shock from that!\rIt might be so shocked, it'll erupt!\nNah, that can't happen!\rSee ya, \v0103\x0001!\nSay hi to that zippity Trainer buddy!\r
Gwogobo gwobobobo!\r
HEATRAN disappeared into\nthe volcano...
                                                                                                                               