num: 25
seed: 0xe94a
Welcome!\nHow may I serve you?
Please come again!
Is there anything else I may do\nfor you?
You don't have enough money.
\v0108\x0000? Certainly.\nHow many would you like?
\v0108\x0000, and you want \v0133\x0001.\nThat will be $\v0137\x0002. OK?
Here you are!\nThank you!\rYou put away the \v0108\x0000\nin the \v011b\x0001 Pocket.
You have no more room for this\nitem.
CANCEL
$\v0135\x0000
You also get a Premier Ball as\nan added bonus.
Thank you! We'll send\nthe \v010a\x0000 to your PC.
Your PC is full.\nYou have no more room for goods.
You placed the \v010a\x0000\nin the Seal Case.
The Seal Case is full.\nYou have no more room for Seals.
BUY
SELL
SEE YA!
Money
$\v0137\x0000
In Bag: \v0134\x0000
x\v0133\x0000
$\v0137\x0000
YES
NO