num: 26
seed: 0x165
Communicating. Please standby...
The \v0108\x0000 went in!
\v0103\x0000
It'll burn! Stir it!
Too fast! Overflow!
It'll burn! Hurry!
Slow down a little!
Quick! Quick!
    
RESULTS
Time
\v0133\x0000:\v0133\x0001:\v0133\x0002
Overflowed
\v0135\x0000 time
Burned
\v0135\x0000 times
Poffins made:
\v0109\x0003 Lv. \v0133\x0001 x \v0133\x0002
      
      
\v0103\x0000 put away the\n\v0109\x0003(s) in the case.
Would you like to keep cooking\nPoffins?
Someone has dropped out.\nCooking will be canceled.
Please choose the Berry you want to\ncook from your Bag.
The Poffin Case is full.
There isn't a Berry to cook.