num: 44
seed: 0xf420
PAL PAD
CHECK FRIEND ROSTER
REGISTER FRIEND CODE
\v0103\x0000's CODE
EXIT
FRIEND ROSTER
\v0103\x0000
CANCEL
DETAILS
REWRITE NAMES
DELETE
CANCEL
What would you like to do\nwith \v0103\x0000's data?
RECORD WITH \v0103\x0000
GROUP
BATTLE RECORD
WIN: \v0135\x0000
LOSE: \v0135\x0000
POKéMON TRADES
\v0135\x0000 time
DATE LAST PLAYED
\v014a\x0001 \v0133\x0002, \v0135\x0000
\v0103\x0000's CODE
By exchanging Friend Codes\nwith other players, you may\ntrade and battle with them\nover Nintendo WFC.
To obtain your Friend Code,\nplease log on to the\nNintendo WFC.
\v0135\x0001 \v0135\x0002 \v0135\x0003\n\v0103\x0000 will be registered.
The Friend Code is wrong.\n\v0135\x0001 \v0135\x0002 \v0135\x0003
\v0135\x0001 \v0135\x0002 \v0135\x0003
\v0103\x0000 will be deleted.\nAre you sure about this?
Your Friend Roster is full!
That Friend Code has already been\nregistered before.
\v0103\x0000's Friend Code:\n\v0135\x0001 \v0135\x0002 \v0135\x0003
CHECK FRIEND CODE
Register \v0103\x0000 in your\nPal Pad?
Your Friend Roster is full.\nWill you delete someone?
Give up on registering\n\v0103\x0000?
Delete \v0103\x0000's data from\nyour Friend Roster?





\v0103\x0000
\v0135\x0000 times