num: 10
seed: 0x242b
Welcome!\rYou may exchange your Coins for\nfabulous prizes here!\r
Which prize would you like?
So your choice is\nthe \v0108\x0000?
So your choice is \v0108\x0000:\n\v0106\x0001?
Here you go!
You don't have enough Coins.\r
There isn't any room available for\nthat \v0108\x0000.\r
Oh, is that so? \nPlease come back with some Coins!
I love words like “walk-off,\ngrand-slam home run.”
They have prizes I really want, but\nit'd be tough saving up the Coins.