num: 8
seed: 0xe6e4
Look! These are Poké Balls!\nLet's battle using these!\r
\vff00\x0003Tiny Leaf Pokémon TURTWIG\vff00\x0000!\nWill you take this Pokémon?
\vff00\x0001Chimp Pokémon CHIMCHAR\vff00\x0000!\nWill you take this Pokémon?
\vff00\x0002Penguin Pokémon\vff00\x0000 \vff00\x0002PIPLUP\vff00\x0000!\nWill you take this Pokémon?
                        
                       
                         
Eh...?\nWhich one do you want, then?