num: 2
seed: 0x2443
\v0103\x0000: What are you doing?\nYou're not supposed to be here.\rThere's nothing here anyway.\rIf anything were to happen, it's in\nmy good hands.\rI've got my trusty Pokémon with me\nfor one.\rAnd more than anything, I'm tough,\nand you know it!
\v0103\x0000: What'd I say?\nI told you I'll be OK by myself.\rIf you haven't gone yet, go\nchallenge the Sunyshore Gym.\rI have a feeling things are going\nto keep getting tougher.\rIt could be rough if you don't\ncollect up some Gym Badges.