num: 85
seed: 0x2e3d
Started from \v0104\x0000.
\v014a\x0000 \v0133\x0001
Sunday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Rested comfortably at home.
Left the Research Lab.
Used a PC Box.
Shopped at a Poké Mart.
Did lots of shopping at a Poké Mart.
Sold a little at a Poké Mart.
Sold a lot at a Poké Mart.
Did some business at a Poké Mart.
\v0120\x0000 was too tough...
Beat \v0120\x0000's \v0143\x0001!
Beat Elite 4 \v0143\x0000!
Defeated the Champion, \v0143\x0000!
Arrived in \v0104\x0000.
Got through \v0104\x0000.
Departed from \v0104\x0000.
Exited from \v0104\x0000.
Had fun at the Game Corner.
Went wild on the Safari Game.
Dug for Treasure underground.
Built a Secret Base underground.
\v0142\x0000 was obtained.
Used Cut at \v0104\x0000.
Flew to \v0104\x0000.
Used Surf at \v0104\x0000.
Used Strength at \v0104\x0000.
Used Flash at \v0104\x0000.
Used Rock Smash at \v0104\x0000.
Used Waterfall at \v0104\x0000.
Used Rock Climb at \v0104\x0000.
Used Defog at \v0104\x0000.
Used Dig at \v0104\x0000.
Lured Pokémon with a sweet aroma.
Warped to \v0104\x0000.
Shared HP using Softboiled.
Shared HP using Milk Drink.
Caught \v0145\x0000 (\v0121\x0001).
\v0145\x0000 was caught (\v0121\x0001).
Caught a male \v0145\x0000.
Caught a female \v0145\x0000.
\v0145\x0000 was defeated (\v0121\x0001).
Defeated \v0145\x0000 (\v0121\x0001).
Defeated a male \v0145\x0000.
Defeated a female \v0145\x0000.
Battled \v0143\x0001 at \v0146\x0000.
Beat \v0143\x0001 at \v0147\x0000.
Beat \v0143\x0001 at \v0148\x0000.
Met \v0149\x0000's \v0143\x0001!
\v0143\x0001
Beat \v014b\x0000 (Single).
Lost to \v014b\x0000 (Single).
Tied \v014b\x0000 (Single).
Beat \v014b\x0000 (Double).
Lost to \v014b\x0000 (Double).
Tied \v014b\x0000 (Double).
Beat \v014b\x0000 & \v014b\x0001 (Multi).
Lost to \v014b\x0000 & \v014b\x0001 (Multi).
Tied \v014b\x0000 & \v014b\x0001 (Multi).
Beat \v014b\x0000 (Mix).
Lost to \v014b\x0000 (Mix).
Tied \v014b\x0000 (Mix).
Beat \v014b\x0000 & \v014b\x0001 (Mix).
Lost to \v014b\x0000 & \v014b\x0001 (Mix).
Tied \v014b\x0000 & \v014b\x0001 (Mix).
Greeted \v0143\x0000 in Union Room.
Got \v0144\x0001 from \v0143\x0000.
Drew pictures with others.
Got \v0144\x0000 in a friend trade.
Chatted with others.
Beat \v0143\x0000 (Union).
Lost to \v0143\x0000 (Union).
Tied \v0143\x0000 (Union).
Mixed records with friends.
Placed no. \v0132\x0000 in a Contest.
Made Poffins in a group.
Got \v0143\x0000's \v0144\x0001 (GTS).
Won at the Battle Tower!