num: 67
seed: 0x66d4
Target \v0132\x0003
Effect No. \v0134\x0000
Effect name \v0106\x0001
No. of turns \v0133\x0002
Shadow (perspective)
Shadow (direct)
Shadow (basic)
AA to BB
BB to AA
A to B
A to D
C to B
C to D
B to A
B to C
D to A
D to C
A to C
C to A
B to D
D to B
Ball Capsule PC
Ball Capsules (fewer)
Ball Capsules (full)
Egg hatch Demo
Egg demo: MANAPHY
Dummy
Sleep
Poison
Burned
Frozen
Paralysed
Confusion
Infatuation
Level Up
Trainer's item
Pokémon Berry
Rare effect
Up
Down
Recover
Out of the screen
Into the screen
Item Pocket
Weather: Mist
Weather: Rain
Weather: Hail
Weather: Sandstorm
Weather: Sunny
----------
----------
Call decoy
Delete decoy
Bait: Pleased
Bait: Eat
Upset
Turn: Curse
Turn: Nightmare
Turn: Leech Seed
Turn: Bind
Turn: Wrap
Turn: Fire Spin
Turn: Magma Storm
Turn: Clamp
Turn: Whirlpool
Turn: Sand Tomb
Turn: Ingrain