num: 22
seed: 0xb4b2
TV\n
TV0
TV1
TV2
TV3
TV4
TV5
TV6
TV7
TV8
Clear player's data
Clear another player's data
Confirm data
Questionnaire (player)
Observation (player)
Records (player)
Questionnaire \v0132\x0000 (another player)
Observation \v0132\x0000 (another player)
Records \v0132\x0000 (another player)
Id\v0133\x0000　Preview\v0132\x0001 \v0133\x0002/\v0133\x0003/\v0133\x0004 CRC \v0136\x0005
No data
ID: \v0136\x0000 \v0103\x0001 Country: \v0133\x0002