num: 129
seed: 0xd8d3
Hello, and welcome to\nthe Pokémon Center.\rWe restore your tired Pokémon\nto full health.\rWould you like to rest your Pokémon?
OK, I'll take your Pokémon for a few\nseconds.
Thank you for waiting.\rWe've restored your Pokémon to full\nhealth.\r
We hope to see you again!
Hello, and welcome to\nthe Pokémon Center.\rWe restore your tired Pokémon\nto full health.\rWould you like to...\r
Th-that Trainer Card!\rThat sparkling color!\nAnd all those stars!\rI've seen several Trainers with Silver\nTrainer Cards up to now...\rBut you're the first to top them\nwith that Trainer Card.\rPlease, \v0103\x0000, may I have\nthe honor of healing your Pokémon?
It's great to see you, \v0103\x0000!\nYou want the usual, am I right?
I will be pleased to take your\nPokémon for a few seconds.
Thank you for waiting.
We hope to see you again!
Your Pokémon may be infected with\nthe Pokérus.\rLittle is known about the Pokérus\nexcept that they are microscopic\flife-forms that attach to Pokémon.\rWhile infected, Pokémon are said to\ngrow exceptionally well.
\v0103\x0000 is out of battle-ready\nPokémon!\r\v0103\x0000's vision dimmed!
            
Would you like to save the game?
There is already a saved file.\nIs it OK to overwrite it?
Saving...\nDon't turn off the power.
\v0103\x0000 saved the game.
Warning!\nThere is already a saved game file.\rIf you save now, the other file's\nadventure, including items and\fPokémon, will be entirely lost.\rAre you sure you want to save now\nand overwrite the other save file?
Save error.
Saving...\nDon't turn off the power.
There is already a saved game file.\nIt is impossible to save.\rPlease refer to the Instruction\nBooklet for details.\rPress Up + SELECT + B Button on\nthe title screen if you want to erase\fthe current saved game file.
Saving a lot of data...\nDon't turn off the power.
Want to give a nickname to the\n\v0100\x0000?
                 
\v0103\x0000 obtained the Pokétch\napp \v0118\x0001.
Obtained the \v0108\x0000!
\v0103\x0000 installed the app on\nthe Pokétch.\r
Too bad!\nThe Bag is full...
\v0103\x0000 obtained\nthe \vff00\x0002\v0108\x0001\vff00\x0000!
\v0103\x0000 obtained\nthe \vff00\x0001\v0108\x0001\vff00\x0000!
\v0103\x0000 put the \v0108\x0001\nin the \v011f\x0002 Pocket.
\v0103\x0000 put away the\n\v011f\x0001 in the Fashion Case.
\v0103\x0000 booted up the PC.\r
Which PC should be accessed?
The Pokémon Storage System\nwas accessed.\r
Accessed \v0103\x0000's PC.\r
Rowan's words echoed...\n\v0103\x0000! There's a time and\fplace for everything! But not now.
Welcome!\nWhat do you need?
                     
There! All happy and healthy!\nGood luck and take care!
Mom: \v0103\x0000!\nWelcome home.\rIt sounds like you had quite the\nexperience out there.\rMaybe you should take a quick\nrest so you can relax.\r...\n...
Mom: Oh, good! You and your\nPokémon are looking great.\rOh, yes, I heard from Professor\nRowan.\rHe said that a Pokémon's energy is\nmeasured in HP (Hit Points).\rIf your Pokémon lose their HP,\nyou can restore it at any\fPokémon Center.\rIf you're going to travel far away,\nthe smart Trainer stocks up on\fPotions at the Pokémon Mart.\rMake me proud, honey!\nTake care!
Mom: Oh, good! You and your\nPokémon are looking great.\rOh yes, \v0103\x0000, your Pokémon\nwill faint if it runs out of HP.\rIf your Pokémon loses its HP, come\nhome before it faints.\rIt will be healed to full health by\ntaking a rest.\rWell, honey, make me proud!\nTake care!
First, let's restore your Pokémon\nto full health.
Your Pokémon have been healed\nto perfect health.
Please visit a Pokémon Center when\nyour Pokémon's HP goes down.\rIf you're planning to travel any\ndistance, you should stock up on\fPotions at a Pokémon Mart.\rGood luck, Trainer!
There is a sweet scent in the air...
There is a sweet scent in the air...\r
The bark is slathered with Honey...
The bark is slathered with Honey...\r
Slather the bark with Honey?
The bark was slathered with Honey.
There's no Mail in the Mailbox.\r
The Mail's content will be lost.\nTake it back anyway?
Not even a nibble...
The Pokémon got away...
Reeled it in too quickly...
Landed a Pokémon!
                                       
                  
                
           
                                                                           
                                                                           
                                                                                            
                                                                                     
\v0101\x0000 survived the poisoning.\nThe poison faded away!\r
It's an air vent that exchanges\nthe underground tunnels' air.
♂
♀
There appears to be nothing here...
The sweet scent faded for some\nreason...
                                  
Ride your Bike?
Get off your Bike?
                    
Oh?
\v0100\x0000 hatched from the Egg!
Would you like to nickname the newly\nhatched \v0100\x0000?
Repel's effect wore off...
Obtained the \v0108\x0000!
Obtained the \v0108\x0000 \v0133\x0001!
I'm very sorry.\rWe are working underground right now.\nIt's off-limits to the public.\rPlease try later on.
The \vff00\x0002Digital Watch\vff00\x0000 app displays\nthe current time.\r
The \vff00\x0002Calculator\vff00\x0000 app can handle\ncalculations up to ten digits.\r
The \vff00\x0002Memo Pad\vff00\x0000 app can be used for\njotting down quick notes.\r
The \vff00\x0002Pedometer\vff00\x0000 app counts the number\nof steps you've walked.\r
The \vff00\x0002Pokémon List\vff00\x0000 app lets you\ncheck on the status of your team.\r
The \vff00\x0002Friendship Checker\vff00\x0000 app identifies\nthe Pokémon that like you.
The \vff00\x0002Dowsing Machine\vff00\x0000 app locates\nunseeable items.\r
The \vff00\x0002Berry Searcher\vff00\x0000 app indicates\nthe locations of ripe Berries.
The \vff00\x0002Day-Care Checker\vff00\x0000 app shows\nthe Pokémon left with the Day Care.
The \vff00\x0002Pokémon History\vff00\x0000 app shows\nthe most recently obtained Pokémon.
The \vff00\x0002Counter\vff00\x0000 app can be used\nto count up to 9,999.
The \vff00\x0002Analog Watch\vff00\x0000 app displays\nthe current time.
The \vff00\x0002Marking Map\vff00\x0000 app allows the\nplacement of markers.\r
The \vff00\x0002Link Searcher\vff00\x0000 app determines\nthe availability of wireless hot spots.\r
The \vff00\x0002Coin Toss\vff00\x0000 app can be used\nto make fair decisions.
The \vff00\x0002Move Tester\vff00\x0000 app is used to check\nhow moves match up.\r
The \vff00\x0002Calendar\vff00\x0000 app is a monthly\ncalendar with date reminders.
The \vff00\x0002Dot Artist\vff00\x0000 app gives players\nfree reign to their creativity.
The \vff00\x0002Roulette\vff00\x0000 app can be customized\nto make an original roulette.
The \vff00\x0002Trainer Counter\vff00\x0000 app tracks\nthe Pokémon Radar's rankings.\r
The \vff00\x0002Kitchen Timer\vff00\x0000 app is a 99-minute\ntimer.
The \vff00\x0002Color Changer\vff00\x0000 app can change\nthe Pokétch display color.
The \vff00\x0002Matchup Checker\vff00\x0000 app shows the\naffinity of Pokémon to each other.\r
The \vff00\x0002Stopwatch\vff00\x0000 app keeps precise\ntime.\r
The \vff00\x0002Alarm Clock\vff00\x0000 app operates\non a 24-hour system.\r
Obtained \v0119\x0000.
The \v0119\x0000 was sent to\nthe underground PC.
There is text engraved in the back\nof the obtained Plate...\r“When the universe was created,\nits shards became this Plate.”\r
There is text engraved in the back\nof the obtained Plate...\r“The power of defeated giants\ninfuses this Plate.”\r
There is text engraved in the back\nof the obtained Plate...\r“Two beings of time and space set\nfree from the Original One.”\r
There is text engraved in the back\nof the obtained Plate...\r“Three beings were born to bind\ntime and space.”\r
There is text engraved in the back\nof the obtained Plate...\r“Two make matter, and three make\nspirit, shaping the world.”\r
There is text engraved in the back\nof the obtained Plate...\r“The Original One breathed alone\nbefore the universe came.”\r
There is text engraved in the back\nof the obtained Plate...\r“The powers of Plates are shared\namong Pokémon.”\r
There is text engraved in the back\nof the obtained Plate...\r“The rightful bearer of a Plate\ndraws from the Plate it holds.”\r
Ball Capsules can't be used because\nyou don't have any Seals.\r
Saving the game again...\nDon't turn off the power.
Good morning!\nWelcome to the Pokémon Center.\rWe restore your tired Pokémon\nto full health.\rWould you like to rest your Pokémon?
Hello, and welcome to\nthe Pokémon Center.\rWe restore your tired Pokémon\nto full health.\rWould you like to rest your Pokémon?
\v0103\x0000's Azure Flute is making\na sound!\rWould you like to blow into the\nAzure Flute?
\v0103\x0000 blew the Azure Flute.\r
A glowing stairway appeared!
The Azure Flute echoed hollowly...\rIt appears to be meaningless using\nthe Azure Flute here...
\v0103\x0000 put the \v0108\x0001\nin the \vff00\x0002\v011b\x0002\vff00\x0000 Pocket.\r
\v0103\x0000 put away the\n\v011f\x0001 in the Fashion Case.\r
The \v0119\x0000 was sent to\nthe underground PC.\r