num: 4
seed: 0xb45f
It's a statue of a Pokémon.\nIt seems to exude power...\r\v0103\x0000 read the engraved\nwriting...\rA body of rock.\rA body of ice.\rA body of steel.\rWhen gathers the three Pokémon,\nthe king shall appear.
It's a statue of a Pokémon.\nIt seems to exude power...\r\v0103\x0000 read the engraved\nwriting...\rA body of rock.\rA body of ice.\rA body of steel.\rWhen gathers the three Pokémon,\nthe king shall appear.\r...\n...\r
...Zut zutt!\r
REGIGIGAS disappeared from view...