num: 4
seed: 0x240a
\v0103\x0000: ...I'd better take\nmy Bag and Journal, too...\r
Oh, hey, \v0103\x0000!\rWe're going to the lake!\nI'll be waiting on the road!\fIt's a $10 million fine if you're late!\r
It's a Wii!\nIt's controlled by a Wii Remote!
\v0103\x0000 checked the PC screen.\rAdventure Rule No. 1\nThe X Button opens the menu!\rAdventure Rule No. 2\nRecord your progress with SAVE.\rThere is nothing else on here...