num: 7
seed: 0x7403
Hello.\nThis is the Canalave Library.\rPlease keep quiet while you're on\nthe premises.
H-hello!\nThis is the Canalave Library.\rPlease keep quiet while you're on\nthe premises.\rIt certainly wasn't me who screamed,\r\vff01\x00c8“Gyaaah!!”\vff01\x0064\r\vff01\x00c8\vff01\x0064or shouted,\r\vff01\x00c8“Help meee!!”\vff01\x0064\r\vff01\x00c8\vff01\x0064No, really, that wasn't me\nscreaming!
...\r
What is it? Please don't disturb\nme when I'm reading.\r
I've been asking people not to\ndisturb me while I'm reading...\rI shouldn't even have bothered...\nI'm all agitated now!
The ceiling-high bookshelves are\ncrammed with books.
The shelves are lined with books\nworn from being read by many people.