num: 42
seed: 0x993a
I'm the Day-Care Man.\rWe look after the precious Pokémon\nof other Trainers.\rIf you'd like us to raise your\nPokémon, have a word with my wife.
Ah, it's you!\rWe were raising your Pokémon,\nand my goodness, were we surprised!\rYour Pokémon was holding an Egg!\rWe don't know how it got there,\nbut your Pokémon had it.\rYou do want it, don't you?
Ah, it's you! Good to see you.\nYour \v0100\x0000's doing just fine.
Well then, I'll hang on to it.\nThanks!
You have no room for it right now...\nCome back when you've made room.
\v0103\x0000 received the Egg from\nthe Day-Care Man.
You take good care of it.
By the way, I saw your \v0100\x0000\ncavorting with \v0103\x0001's\f\v0100\x0002.\rI may even have seen it receiving\na piece of Mail.
If you want to pick up your Pokémon,\nhave a word with my wife.
Ah, it's you!\nGood to see you!\rYour \v0100\x0000 and \v0100\x0001\nare doing just fine.\r
I really will keep it.\nYou do want this, yes?
The two seem to get along very well.
The two seem to get along.
The two don't seem to like each\nother much.
The two prefer to play with other\nPokémon more than with each other.
I'm the Day-Care Lady.\nWe can raise Pokémon for you.\rWould you like us to raise your\nPokémon?
Which Pokémon should we raise for\nyou?\r
Fine, we'll raise your \v0100\x0000\nfor a while.\rCome back for it later.\r
We can raise two of your Pokémon.\nWould you like us to raise another?
Ah, there you are!\nMy husband was looking for you.
Oh, fine, then.\nCome again.
You don't have enough money...
Do you want to take back the other\none, too?
Very good.\nCome again.
Ah, it's you! Good to see you.\nNow, about your Pokémon...\r
By level, your \v0100\x0000 has\ngrown by about \v0133\x0001.\r
Your Pokémon team is full.\nMake room, then come see me.
Which Pokémon will you take back?
If you want your \v0100\x0000 back,\nit will cost $\v0135\x0001.
Excellent!\nHere's your Pokémon.\r
\v0103\x0001 took \v0100\x0000 back\nfrom the Day-Care Lady.\r
Oh? But you only have one\nPokémon with you.\rYou can't go off without a Pokémon.\nCome back another time.
Do you want your Pokémon back?
If you leave me that Pokémon,\nwhat are you gonna battle with?\rCome back another time.
Huh? Now, now.\rIf you leave that Pokémon with\nme, you'll be left with just one.\rYou will be better off if you catch\nsome more, if I do say so myself.
Now, now.\nThat is merely an Egg!
Fine, we'll raise your \v0100\x0000\nfor a while.\rCome back for it later.
Huh?
Lv. \v0134\x0001
\v0100\x0000♂
\v0100\x0000♀
\v0100\x0000