num: 18
seed: 0x5c96
All right, thanks for your patience!\nLet's begin the Visual Competition!\r
Dexter: Entry number 1!\n\v0103\x0000!\r\v0103\x0000 has entered the Contest\nwith \v0100\x0001!\r
Dexter: Entry number 2!\n\v0103\x0000!\r\v0103\x0000 enters our Contest with\n\v0100\x0001!\r
Dexter: Entry number 3!\n\v0103\x0000!\r\v0103\x0000 is in the Contest with\n\v0100\x0001!\r
Dexter: Entry number 4!\n\v0103\x0000!\r\v0103\x0000's Contest hopes ride\nwith \v0100\x0001!\r
The Dance Competition is next!\nIs everyone up and ready for this?!\r
    
    
    
    
    
    
             
                                                   
    
                                                                                   
                     
OK, let's watch the reactions of the\naudience toward the Pokémon involved\fin this practice session!\rI'll pass over the MC duties to\nDexter and call this a rehearsal!\fDexter: Sure thing! I've got it!\r