num: 6
seed: 0x2406
\v0103\x0001's mom: Oh, hi,\n\v0103\x0000.\rAre you looking for \v0103\x0001?\rHe was gone for a second, but then\nhe came running right back home.\rHe just can't sit still, that boy.\nI wonder who he takes after?
\v0103\x0001's mom: Oh, hi,\n\v0103\x0000.\rDid you come calling on \v0103\x0001?\rHe was gone for a second, but then\nhe came running right back home.\rHe just can't sit still, that boy.\nI wonder who he takes after?
\v0103\x0001's mom: That kid rocketed\noff again like usual.\rI'd guess he would be out on\nRoute 201 by now?\rHe just can't sit still, that boy.\nI wonder who he takes after?
\v0103\x0001's mom: \v0103\x0001\nshould be out on Route 201 by now.\rHe just can't sit still, that boy.\nI wonder who he takes after?
\v0103\x0001's mom: Oh, you've\nbecome friends with a Pokémon, too.
\v0103\x0001's mom: \v0103\x0001\ntook off like a rocket as usual.\rHe was shouting something about\nbecoming the greatest Trainer ever...\rHe just can't sit still, that boy.\nI wonder who he takes after?