num: 49
seed: 0xb6f3
HP/PP
RESTORE
STATUS
HEALERS
     
    
BATTLE ITEMS
POKé BALLS
Item used last
\v0108\x0000
x\v0134\x0000
\v0108\x0000
x\v0134\x0000
\v0108\x0000
x\v0134\x0000
\v0108\x0000
x\v0134\x0000
\v0108\x0000
x\v0134\x0000
\v0108\x0000
x\v0134\x0000
   
HP/PP
RESTORE
STATUS
HEALERS
POKé BALLS
BATTLE ITEMS
/
\v0132\x0000
\v0132\x0000
USE
\v0108\x0000
x\v0134\x0000
It won't do any good to use that!
              
\v0101\x0000 is getting\npumped!
\v0101\x0000's Attack\nrose!
\v0101\x0000's Special Attack\nrose!
\v0101\x0000's Speed\nrose!
\v0101\x0000's Special Defense\nrose!
\v0101\x0000's Defense\nrose!
\v0101\x0000's accuracy\nrose!
The \v0108\x0000 was used!
It's no good! It's impossible to aim\nwhen there are two Pokémon!
There is no room left in the PC!
\v0106\x0001's effect prevents\nthe item's use on \v0101\x0000!
It's no good! It's impossible to aim\nat a Pokémon that's not in sight!
It's no good! It's impossible to aim\nat a Pokémon that's not in sight!