num: 4
seed: 0x3443
What do you want?\rAre you one of those nitwits we\nfooled into guarding the entrance?\rBah, it doesn't matter who you are.\nIt's too late to make any difference.\rThings are going to get really\ninteresting now.\rAll the legendary Pokémon are going\nto be brought to our HQ in Veilstone!
Even Team Galactic has no use for\nMAGIKARP! Worthless, all of them!
Hahaha!\nNext stop, Lake Verity!\rThe closest civilization is that hick\ntown called Twinleaf!\rWe can roll in there completely\nunopposed!
A MAGIKARP is weakly flopping about...