num: 112
seed: 0x2c1
USE
TOSS
REGISTER
GIVE
CHECK TAG
CONFIRM
WALK
   
CANCEL
   
   
     
    
   
    
    
CHECK
  
DESELECT
   
     
 
 
  
---
 
 
  
  
 
 
    

    
          
         
   
\v0134\x0000
x
  
      
CLOSE BAG
\v0108\x0000 is\nselected.
                     
            
Move the \v0108\x0000 where?
The \v0108\x0000 can't be held.
                         
                 
                  
                
                             
Toss out how many\n\v0108\x0000(s)?
Threw away \v0133\x0001 \v0108\x0000.
Is it OK to throw away\n\v0134\x0001 \v0108\x0000?
                                        
You can't dismount your Bike here.
Your Coins: \v0136\x0000
Booted up a TM.\v0202\x0003\v0202\x0004\n
Booted up an HM.\v0202\x0003\v0202\x0004\n
It contained\n\v0106\x0000.\rTeach \v0106\x0000\nto a Pokémon?
\v0103\x0000 used the\n\v0108\x0001.
Since a Repel's effects still linger,\nyou can't use this now.
\v0103\x0000 used the\n\v0108\x0001.\rWild Pokémon will be lured.
\v0103\x0000 used the\n\v0108\x0001.\rWild Pokémon will be repelled.
The Box is full.
            
No.\v0133\x0000\v0106\x0001
No.\v0133\x0000\v0106\x0001
\v0133\x0000\v0106\x0001
      
                              
             
                       
\v0108\x0000? Oh, no.\nI can't buy that.
\v0108\x0000?\nHow many would you like to sell?
I can pay $\v0137\x0000.\nWould that be OK?
Turned over the \v0108\x0000\nand received $\v0137\x0001.
MONEY
$\v0137\x0000
x\v0133\x0000
$\v0137\x0000
Yes
No
x\v0134\x0000
    
PP
POWER
ACCURACY
CATEGORY
\v0133\x0000
\v0134\x0000
Seals: \v0135\x0000
Accessories: \v0134\x0000\nBackdrops: \v0133\x0001
Close Bag
PLANT
OPEN
Saved Battle Points\n\v0135\x0000BP
TYPE
A Key Item in the Bag can be assigned\nto this button for instant use.
                  
             
                  
          
               
                            
The battery has run dry!\nFor it to recharge, you need to walk\fanother \v0133\x0000 steps.
The grassy patch remained quiet...
No. of Poffins:
\v0134\x0000/100
Please choose the Berry you want to\ncook from your Bag.
It can't be used when you have\nsomeone with you.