num: 10
seed: 0x596e
Hello.\nI'm pleased to meet you.\rI'm Maylene, and I'm the Gym\nLeader.\rI don't really know what it means to\nbe strong, or how I got to be the\fGym Leader.\rBut I will do the best I can as the\nGym Leader.\rI take battling very seriously.\nWhenever you're ready!\r
...OK.\nYou win.\rThat was a tough loss.\nI learned a lot from it.\rPlease, accept this Gym Badge.\r
\v0103\x0000 received\nthe Cobble Badge from Maylene.
Um...\nI should explain about that Badge.\rIf you have that official Pokémon\nLeague Badge, you can use the hidden\fmove Fly outside of battle.\rOh, and please take this as well.\r
That \v0108\x0000 contains\nthe move \v0106\x0001.\rUm... That move inflicts damage,\nand it robs the target's HP.
Gee, I'm hungry...\rOh, sorry, it's nothing.\nI didn't say anything.\r\v0103\x0000, I can't explain what\nit means to be strong.\rI don't know how much effort goes\ninto being strong...\rBut being with Pokémon lets us\nkeep making the effort, doesn't it?
Hey, there!\nHow's it going, Champ-to-be?\rThe Gym Leader is a user of\nFighting-type Pokémon.\rShe'd be a terror against Normal-type\nPokémon.\rBut! And it's a big but!\nJust between you and me...\rMaylene, the Gym Leader, said Flying-\nand Psychic-type Pokémon could be\freal trouble for her!
Oh! \v0103\x0000!\nYou've beaten the Gym Leader!\rOf course, I thought you'd win.
Veilstone City Pokémon Gym\nLeader: Maylene\rCertified Trainers:\n\v0103\x0001
Veilstone City Pokémon Gym\nLeader: Maylene\rCertified Trainers:\n\v0103\x0000\f\v0103\x0001