num: 37
seed: 0x241e
Mom: \v0103\x0000!\r\v0103\x0001 came calling for you\na little while ago.\rI don't know what it was about, but\nhe said it was an emergency.\r
Mom: You know how impatient\n\v0103\x0000 is.\rHe took off before I could even\nask what it was about.
Mom: Bye-bye, \v0103\x0000!\nYou take care now!
Mom: But that \v0103\x0000...\nHe always invites you along.
Mom: Oh, yes!\n\v0103\x0000!\rDon't go into the tall grass.\nWild Pokémon might attack you.\rIt would be OK if you had your own\nPokémon, but you don't, so...
Mom: What is it, dear?\nIsn't \v0103\x0000 waiting for you?
Mom: What's up, dear?\r...\rWow.\nI can't believe that happened to you.\rAm I ever glad that both you and\n\v0103\x0000 are unharmed.\rThe professor you mentioned is\nmost likely Professor Rowan of\fSandgem Town.\rI've heard that he is well known for\nhis studies on Pokémon.\rI hear he's also quite intimidating...\r\v0103\x0001, I think you need to\nvisit him in Sandgem Town.\rYou need to properly explain why you\nhad no choice but to use his Pokémon.\rDon't worry!\nI'm sure he will understand.\r
Oh, I know!\n\v0103\x0000, put these on.\r
\v0103\x0000 received a pair of\n\vff00\x0001Running Shoes\vff00\x0000!
Going to Sandgem Town is like an\nadventure in itself, right?\rWith those Running Shoes, you can\nget to faraway places much faster.\rOK...\nLet me read the instructions...\r“Press the B Button and dash\nabout faster than ever before!\r“Put on the Running Shoes and\nblaze new trails of adventure!”\rWell, isn't that just nifty!
Mom: I'll read you the instructions\nfor the Running Shoes...\r“Press the B Button and dash\nabout faster than ever before!\r“Put on the Running Shoes and\nblaze new trails of adventure!”\rWell, isn't that just nifty!
Mom: Welcome home, \v0103\x0000.\nAre you and your Pokémon healthy?\rIt's still early in the morning.\nTake a quick rest, dear.\r
Mom: Welcome home, \v0103\x0000.\nAre you and your Pokémon healthy?\fTake a quick rest, dear.\r
Mom: Welcome home, \v0103\x0000.\nAre you and your Pokémon healthy?\rI just made dinner.\nTake a quick rest, dear.\r
Mom: Welcome home, \v0103\x0000.\nAre you and your Pokémon healthy?\rIt's so late right now...\nTake a quick rest, dear.\r
Mom: What's up, \v0103\x0000?\r...\rWow. Professor Rowan asked you\nto do something that big.\rOK, dear, go for it!\nYour mom's got your back!\rOh, I know! \v0103\x0000, I've got\nsomething that you'll find useful.\r
That's a Journal. It keeps a record\nof your daily events.\rCheck it, and you'll be able to\nremember what you did last.\r
Gee, a journey full of adventure...\nI envy you, kiddo.\rPlus, you're not alone.\nYou have your Pokémon with you.\fI wish I could go instead!\r
I'm just joking, dear!\nYup, \v0103\x0000!\rI'll be all right by myself, so you\ngo and enjoy your adventure!\rWhen you're exposed to new things,\nand experience new sensations...\fIt makes your mother happy too.\r...But come back sometimes.\rI would like to see the kinds of\nPokémon you've caught, dear.\r
\v0103\x0001's mom: Excuse me.\nIs my little \v0103\x0001 here?\r
Mom: Oh?\nNo, he's not...\r
\v0103\x0001's mom: Oh...\nThen, he must have left already...\fWhat to do...\rThat boy shouted about going on an\nadventure, then he bolted.\rHe's so headstrong and reckless...\nI at least wanted him to take this...\r
Mom: Not to worry, \v0103\x0000 will\ndeliver that to him.\r
Won't you, \v0103\x0000?\r
\v0103\x0001's mom: Oh, really?\nYou'd do that for me?\r\v0103\x0000, please take this to\n\v0103\x0001 for me.\r
\v0103\x0001's mom: Oh, really?\nYou'd do that for me?\r\v0103\x0000, please take this to\n\v0103\x0001 for me.\r
\v0103\x0001's mom: Let me think...\rKnowing my boy, he would probably\nhead straight to Jubilife City...\rOK, please take that to my\n\v0103\x0001.\r
Mom: Bye-bye, \v0103\x0000!\nEnjoy your adventure!\r
Mom: Bye-bye, \v0103\x0000!\nEnjoy your adventure!
MC: Here we are!\nIt's the Contest Digest!\rThe winner of today's Normal Rank\nCute Contest is...\rBrooke, who entered a breathtakingly\ncute Pokémon!\rThat's all the time we have today!\nUntil next time!
MC: Here we are!\nIt's the Contest Digest!\rThe winner of today's Normal Rank\nSmart Contest is...\rWestley, who won with his bright spark\nof a Pokémon!\rThat's all the time we have today!\nLet's meet again!
MC: Here we are!\nIt's the Contest Digest!\rThe winner of today's Normal Rank\nTough Contest is...\rDominic, who overwhelmed with his\nawesomely buffed Pokémon!\rThat's all the time we have today!\nLet's meet again!
Mom's favorite dessert is in\nthe refrigerator.
Mom's kitchen is spotless!\nYou can see your face on the floor!
This is where Mom does all her\ndelicious cooking.
Mom: \v0103\x0000!\r\v0103\x0001 came looking for you\na little while ago.\rI don't know what it was about, but\nhe was shouting about you needing\fto get on a ship at Snowpoint City.\rYou know how impatient he is.\nHe was gone before I could ask.
Mom: \v0103\x0000!\r\v0103\x0001 came looking for you\na little while ago.\rI don't know what it was about, but\nhe was shouting about you needing\fto get on a ship at Snowpoint City.\rYou know how impatient he is.\nHe was gone before I could ask.\rAnyway, how's it going, kid?\rIs your project with Professor Rowan\ncoming along?