num: 5
seed: 0xa06b
                                                                                                                                   
                                                                                                       
                                                                                                           
\v0103\x0000 scurried to\na Pokémon Center, protecting\nthe exhausted and fainted\nPokémon from further harm...
\v0103\x0000 scurried back\nhome, protecting the exhausted\nand fainted Pokémon from further\nharm...