num: 22
seed: 0xd41b
Julia: Oh, hello.\nYou're quite the nifty Trainer.\rMy husband is a Sailor, and he's off\nworking somewhere far away.\rI long for the day he comes back\nto me.\rAll that waiting gets to be very\nboring every day, though...\rI know! How about you visit me and\ntell me stories every so often?
Starting tomorrow, please visit and\ntell me stories about your travels.
Julia: Today is Monday!\rIt's time to get going on a brand-new\nweek.\rIs there a story that might help\nme perk up?\rMaybe a story about getting splashed\nwith water...
\v011c\x0000 splashed with water...\n...\rThat sounds refreshing!\nIt's made me feel awake!\r
Thank you!\nPlease give this to your Pokémon.\r
\v0103\x0002 received\nthe \v0127\x0003.\r
\v0103\x0002 put\nthe \v0127\x0003\fon \v0100\x0001.\r
Julia: Please tell me another story\ntomorrow.
Julia: Hello!\rOh, this is the \v0100\x0001 I gave\na Ribbon to before.\rI've got lots of Ribbons--you should\nbring other Pokémon.
Julia: Oh...\nYou couldn't think up anything?
Julia: Today is Tuesday!\rThe first date I went on with my\nhusband was on Tuesday, too.\rI remember my heart thumping like\nI was scared, and I guess I was.\rDo you know any story that would\nscare me like that?\rLike something that jumps out\nfrom hiding?
One mean \v011c\x0000 that bursts\nout from a closet?\f...\rYikes!\nThat would be scary!\r
Julia: Sigh...\nI gained a little weight...\rThis dress that my husband bought\nfor me is too tight now...\rThis makes me feel sad...\rMisery does love company.\nSomething that would make me cry?
A tearful \v011c\x0000...\n...\rSniffle... That is so sad...\nI feel desolate, even!\r
Julia: It's Thursday already?\nI lost track of time!\rMy favorite magazine comes out today.\nI'd better go buy it quick!\rDo you know a story about being\nabsentminded?\rLike getting your shoes backward?
The \v011c\x0000 had shoes\non the wrong feet?\r...\nAhahaha! That is so silly!\rHow is it possible to be that\nabsentminded?\r
Julia: Today is Friday!\rMy meager cooking repertoire is\nabout to run out!\rDo you know a story that would\nhelp me get my thoughts in order?\rLike a story about numbers adding\nup perfectly?
You went \v011c\x0000\nshopping and paid $777 including tax?\rThat is a nice number to ring up.\nIt just has a good look to it.\rIt's sure helped me clear my head!\r
Julia: Yawn...\nToday's Saturday...\fI'm feeling lazy and sleepy...\rI wish I had a pillow...\nBut what kind of a pillow?
\v011c\x0000 snuggle pillow...\n...\rIt... It surprisingly may give me\na good night's sleep!\rI wonder if I can buy one somewhere.\r
Julia: Oh, hello! You're on your\nadventure even though it's Sunday!\rWhen I was younger, I remember that\nevery day was like an adventure.\rIt was always fun. I loved the people\naround me... I was happy.\rOh, but I'm happy now, too.\nI love my life with my husband.\fIt's just a different kind of happy.\rSo, what makes you happy?
You love \v011c\x0000?\n...\rUfufu... That says something about\nyou. It puts a smile on my face!\r