num: 8
seed: 0x2466
Thank you so much for participating!\rPlease wait while I save the game.\nDon't turn off the power.
We hope to see you again!
Your Pokémon will be restored to\nfull health.
Up next, opponent pair no. \v0132\x0000.\nAre you ready?
Would you like to save and\nquit the game?
Would you like to cancel your\nBattle Room challenge?
You have chosen to retire from\nthis Battle Room challenge.
Awaiting response from a friend...