num: 117
seed: 0x247a
Welcome to the Battle Tower!\rI am your guide to the Single\nand Double Battle Rooms.\r
Would you like to take the\nBattle Room challenge?
We hope to see you again!
The Battle Tower's Single Battle\nRooms are facilities for conducting\fSingle Battles with three Pokémon.\rSimilarly, the Double Battle Rooms\nare facilities for conducting Double\fBattles with four Pokémon.\rThere are many Battle Rooms in the\nBattle Tower for team battles.\rIn each of the Battle Rooms, seven\nTrainers await your challenge.\rIf you manage to defeat all seven,\nyou will earn Battle Points (BP).\rIf you want to interrupt your\nchallenge, please save the game.\rIf you don't save, you will be\ndisqualified from your challenge.\r
Which Battle Room would you like?\nSingle or Double?
                                                                                                                                                                                        
                                                                                                                                                                                                                                               
                                
Please select the Pokémon you wish\nto enter.\r
Your Pokémon must all be different.\r
Hold items must all be different.\r
I will now show you to the\nBattle Room.
Congratulations!\nYou've beaten all seven Trainers!\r
Congratulations!\nYou've beaten the Tower Tycoon!\rWe present you with these Battle\nPoints in recognition of your talent!\r\v0103\x0000 received\n\v0132\x0001 BP!\r
Saving...\nDon't turn off the power.
We hope to see you again.
We've been waiting for you!\rBefore entering a Battle Room, your\nprogress will be saved.\rSaving...\nDon't turn off the power.
                      
         
Excuse me!\rYou didn't save before you quit your\nchallenge last time.\rBecause of that, you have been\ndisqualified from your challenge!\r
Welcome to the Battle Tower!\rI am your guide to the Multi\nBattle Rooms.\r
Would you like to take the Multi\nBattle Room challenge?
                          
The Battle Tower's Multi Battle\nRooms are facilities for conducting\fMulti Battles.\rFor Multi Battles, you must partner\nwith a Trainer in the tower and enter\fwith two Pokémon each.\rInside the tower is a room named\nthe Battle Salon where you can meet\fother Trainers.\rThere, you must find a Trainer to act\nas your partner in the Multi Battles.\rOnce you have partnered up, you will\nbe shown to a Multi Battle Room.\rIn the Multi Battle Room, seven\ntag teams await your challenge.\rIf you manage to defeat all seven\nteams, you will earn Battle Points.\rIf you want to interrupt your\nchallenge, please save the game.\rIf you don't save, you will be\ndisqualified from your challenge.\rAlso, if you are in a tag team with\na friend, you may not interrupt your\fchallenge.\r
                                                                                                                                                                                                                                                
                                
Would you like to communicate with\na friend and form a tag team?
One Trainer should select\n“BECOME LEADER.”\rThe other Trainer must select\n“JOIN GROUP.”
                          
               
                 
                     
I'll direct you to your\nMulti Battle Room now.
Both Trainers have chosen the\nPokémon \v0100\x0000.\rPlease confer with the other Trainer\nand choose different Pokémon.\r
Both Trainers have chosen the\nPokémon \v0100\x0000 and\f\v0100\x0001.\rPlease confer with the other Trainer\nand choose different Pokémon.\r
I will now show you to the\nBattle Salon.\r
Welcome to the Battle Tower!\rI am your guide to the Wi-Fi\nBattle Rooms.\r
Would you like to take the Wi-Fi\nBattle Room challenge?
The Battle Tower's Wi-Fi Battle Rooms\nare places to conduct battles over\fNintendo Wi-Fi Connection (WFC).\rIn Wi-Fi Battles, you will be battling\nTrainers from around the world over\fNintendo WFC.\rInside the Battle Tower, there are\nmany Battle Rooms.\rIn each of the Battle Rooms, seven\nTrainers await your challenge.\rIf you manage to defeat all seven,\nyou will earn Battle Points.\rDepending on how you do, you may\neven become the room's leader!\rAlso, the Wi-Fi Battle Rooms are\noperated on a ranking system.\rTrainers will go up in rank if they\nkeep winning Wi-Fi Battles.\rContrarily, their rankings could go\ndown if they lose consistently.\rTo raise your rank, keep winning,\nespecially against tougher Trainers.\rIf you want to interrupt your\nchallenge, please save the game.\rIf you don't save, you will be\ndisqualified from your challenge.\r
We hope to see you again!
                                
                                                                                                                                                                                                                                                  
                          
               
                 
                                                     
                            
OK. I'll direct you to your Battle\nRoom now.\rAre you ready?
Would you like to save and\ninterrupt your challenge?
                        
                               
                      
I've downloaded the Rank \v0133\x0000, Battle\nRoom \v0134\x0001's past leader history.\rPlease confirm it on the Performance\nMonitor next to me.
Thank you for playing!\r
Congratulations!\nYou've beaten all seven Trainers!\r
\v0103\x0000, you have also been\npromoted to Rank \v0133\x0001!\r
Saving...\nDon't turn off the power.
Would you like to send these results\nusing Nintendo WFC?
For your 7-win streak, we present\nyou these Battle Points!\r\v0103\x0000 obtained\n\v0132\x0001 BP.\r
                          
Your results were sent out using\nNintendo WFC!\r
It's good to see you back.\rYour previous results were not sent\nout using Nintendo WFC.\rWould you like to send them now?
                                              
                          
           
It's very unfortunate, but you have\nbeen demoted to Rank \v0133\x0000...\r
                                 
                          
                           
Your record will be saved.\nPlease wait.
Congratulations on achieving\nRank \v0133\x0000.\rYour winning Pokémon team has won\nspecial Ribbons for this feat!
Congratulations on achieving \v0134\x0000\nconsecutive wins!\rYour winning Pokémon team has been\ngiven a special award for this feat!
\v0103\x0000 obtained \v0108\x0001!
Congratulations on achieving your\n50-win streak.\rYour winning Pokémon team has won\nspecial Ribbons for this feat!
Yeah, I used to live in a place\ncalled Hoenn.\rThere was a place like this back\nthere, too.
The Wi-Fi Battle Rooms are full of\nsurprises.\rCan you imagine running into an old\nrival who moved far away?\rWho knows what cool encounters you'll\nhave?
They profile you on TV if you set\na good record here.\rThis is my only chance to regain\nmy glory as an Idol!
I trained my little guy till we\ncouldn't take any more.\rHe's going to do a 100-win streak\nfor sure...\rRight, PIKACHU?
PIKACHU: ...
Ooh-la-la!\nYou look tremendously powerful!\rVerily, I shall look forward to\nengaging you in a battle.
There are so many tough Trainers\naround...\rIt's scary, but let's do our best,\nPIKACHU!
PIKACHU: Pichuu! Pichuu!
Congratulations on achieving\na 50-win streak!\rThe Pokémon on your team will be\nprovided with commemorative Ribbons.
Congratulations on advancing to\nRank \v0132\x0000!\rThe Pokémon on your team will be\nprovided with commemorative Ribbons.
Congratulations on defeating\nthe Tower Tycoon!\rThe Pokémon on your team will be\nprovided with commemorative Ribbons.
Congratulations on achieving\nyour \v0134\x0000-win streak!\rPlease accept this trophy for your\nfantastic achievement!\r
...Uh-oh... You've run out of room\nfor decoration goods.\rPlease make room, and come back\nfor your prize.
                                                           
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs are not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs and \v0100\x0001 are\nnot allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, and \v0100\x0002\nare not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\nand \v0100\x0003 are not allowed.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, and \v0100\x0004\fare not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004, and\f\v0100\x0005 are not allowed.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, and \v0100\x0006\nare not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006, and\n\v0100\x0007 are not allowed.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, and \v0100\x0008\fare not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\fand \v0100\x0009 are not allowed.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, and \v0100\x000a\nare not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, \v0100\x000a,\nand \v0100\x000b are ineligible.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, \v0100\x000a,\n\v0100\x000b, and \v0100\x000c\fare not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, \v0100\x000a,\n\v0100\x000b, \v0100\x000c,\fand \v0100\x000d are not allowed.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, \v0100\x000a,\n\v0100\x000b, \v0100\x000c,\r\v0100\x000d, and \v0100\x000e\nare not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, \v0100\x000a,\n\v0100\x000b, \v0100\x000c,\r\v0100\x000d, \v0100\x000e,\nand \v0100\x000f are not allowed.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, \v0100\x000a,\n\v0100\x000b, \v0100\x000c,\r\v0100\x000d, \v0100\x000e,\n\v0100\x000f, and \v0100\x0010\fare not allowed to enter.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, \v0100\x000a,\n\v0100\x000b, \v0100\x000c,\r\v0100\x000d, \v0100\x000e,\n\v0100\x000f, \v0100\x0010,\fand \v0100\x0011 are not allowed.\rPlease come see me when you are\nready.\r
Excuse me!\rYou don't have \v0132\x0000 eligible Pokémon.\rYou must have \v0132\x0000 different Pokémon\nto enter.\rThey also must be holding different\nkinds of items.\rEggs, \v0100\x0001, \v0100\x0002,\n\v0100\x0003, \v0100\x0004,\r\v0100\x0005, \v0100\x0006,\n\v0100\x0007, \v0100\x0008,\r\v0100\x0009, \v0100\x000a,\n\v0100\x000b, \v0100\x000c,\r\v0100\x000d, \v0100\x000e,\n\v0100\x000f, \v0100\x0010,\r\v0100\x0011, and \v0100\x0012\nare not allowed to enter.\rPlease come see me when you are\nready.\r
Thank you so much for participating!\nPlease come again!
Hi, there!\rCan you tell me how you'd introduce\nyourself before a battle, and what\fyou'd say if you won or lost?
OK! So, how would you introduce\nyourself before a battle?
OK! So, what would you say if \nyou lost a battle?
OK! So, what would you say if \nyou won a battle?
Thanks for telling me. You'd say\n“\v011c”...
Oh? You're not going to tell me?\nThat's too bad...
There doesn't appear to be any\ndata yet...\r
DS Wireless Communications will\nbe launched.
We look forward to your next visit.\r