num: 34
seed: 0x9fd6
\v0101\x0000 will perform\nfirst the next turn.
\v0101\x0000 will perform\nbefore \v0101\x0001.
\v0101\x0000 will perform\nlast in the next turn.
\v0101\x0000 will perform\nafter \v0101\x0001.
\v0101\x0000 didn't choose\nthe same Judge as anyone\felse! \vff00\x0001+0\vff00\x0000!
\v0101\x0000 chose the same\nJudge as another Pokémon!\f\vff00\x0001+2\vff00\x0000!
\v0101\x0000 chose the same\nJudge as two other\fPokémon! \vff00\x0001+4\vff00\x0000!
\v0101\x0000 chose the same\nJudge as everyone else! \vff00\x0001+6\vff00\x0000!
\v0101\x0000 performed\n\v0106\x0001!\rIt excited the audience!\n\vff00\x0001+2\vff00\x0000!
\v0101\x0000 didn't pick the\nsame Judge as anyone else!\rThe performance stood out!\n\vff00\x0001+3\vff00\x0000!
\v0101\x0000 chose the same\nJudge as another Pokémon!\rThe performance didn't\nstand out! \vff00\x0001+0\vff00\x0000!\r
If \v0101\x0000's move\nstands out and doesn't\rshare the same Judge with\nanother Pokémon: \vff00\x0001+3\vff00\x0000!\r
\v0101\x0000 can perform\nthe same move twice!
The Voltage score is added\non! \vff00\x0001+\v0132\x0000\vff00\x0000!
\v0101\x0000 chose the same\nJudge as everyone! \vff00\x0001+15\vff00\x0000!
\v0101\x0000 didn't choose\nthe same Judge as all the\fothers! \vff00\x0001+0\vff00\x0000!\r
If \v0101\x0000 chooses the\nsame Judge as everyone\felse: \vff00\x0001+15\vff00\x0000!\r
The Voltage of all the\nJudges went down!
From the previous turn,\n\v0101\x0000 gets \vff00\x0001+\v0132\x0001\vff00\x0000!
\v0101\x0000 got the same\nrating as \v0101\x0001, who\fwent before!
The Voltage is prevented\nfrom rising!
The next turn's order has\nbeen scrambled!
\v0101\x0000 performed\nlast! \vff00\x0001+\v0132\x0001\vff00\x0000!
Higher score earned for low\nVoltage! \vff00\x0001+\v0132\x0000\vff00\x0000!
First performance! \vff00\x0001+2\vff00\x0000!
Last performance! \vff00\x0001+2\vff00\x0000!
The Voltage is prevented\nfrom falling!
The Voltage went up\nconsecutively! \vff00\x0001+3\vff00\x0000!
\v0101\x0000's performance\nis first! \vff00\x0001+1\vff00\x0000!
\v0101\x0000's performance\nis second! \vff00\x0001+2\vff00\x0000!
\v0101\x0000's performance\nis third! \vff00\x0001+3\vff00\x0000!
\v0101\x0000's performance\nis last! \vff00\x0001+4\vff00\x0000!
The performance came after\nthe Voltage peaked! \vff00\x0001+3\vff00\x0000!
\v0101\x0000 has the lowest\nscore! \vff00\x0001+3\vff00\x0000!