num: 73
seed: 0xa8f9
Choose the Judge you want\nto rate the move.
Performance \vff00\x0001no. \v0132\x0000\vff00\x0000!\nWhich move is your choice?
It's the \vff00\x0001last \vff00\x0000performance!\nChoose your move!
To \v0103\x0001, \v0101\x0000\nperformed \v0106\x0002!\r
Oh, no! Someone already\nperformed for that Judge!\r
    
\v0103\x0000 was strongly\nimpressed by the acting of\r\v0101\x0001 and\n\v0101\x0002! \vff00\x0001+2\vff00\x0000!\r
\v0103\x0000 was impressed\nby the performances of\r\v0101\x0001, \v0101\x0002,\nand \v0101\x0003! \vff00\x0001+1\vff00\x0000!\r
Everyone performed for\n\v0103\x0000...\rAnd watered down the\nJudge's impressions.\r
\v0103\x0000 was very\nimpressed by \v0101\x0001's\fperformance! \vff00\x0001+3\vff00\x0000!\r
    
Upon seeing the Cool move\nperformed, \v0103\x0000's\fVoltage went up!\r
Upon seeing the Beauty move\nperformed, \v0103\x0000's\fVoltage went up!\r
Upon seeing the Cute move\nperformed, \v0103\x0000's\fVoltage went up!\r
Upon seeing the Smart move\nperformed, \v0103\x0000's\fVoltage went up!\r
Upon seeing the Tough move\nperformed, \v0103\x0000's\fVoltage went up!\r
    
Upon seeing the Cool move\nperformed, \v0103\x0000's\fVoltage went down.\r
Upon seeing the Beauty move\nperformed, \v0103\x0000's\fVoltage went down.\r
Upon seeing the Cute move\nperformed, \v0103\x0000's\fVoltage went down.\r
Upon seeing the Smart move\nperformed, \v0103\x0000's\fVoltage went down.\r
Upon seeing the Tough move\nperformed, \v0103\x0000's\fVoltage went down.\r
    
    
The audience is getting\npretty excited!\r
The audience is going wild\nwith excitement! \vff00\x0001+\v0132\x0000\vff00\x0000!\r
    
    
    
    
\v0101\x0000 didn't stand\nout very much...\r
\v0101\x0000 caught a\nlittle attention.\r
\v0101\x0000 attracted\ndecent attention.\r
\v0101\x0000 attracted a\nlot of attention!\r
\v0101\x0000 commanded\ntotal attention!\r
OK! It's time for the\nActing Competition!\rShow off the moves that\nexemplify cuteness!\rFour performances each!\nLet's see some enthusiasm!\r
    
OK! It's time for the\nActing Competition!\rShow off the moves that\nexemplify smartness!\rFour performances each!\nLet's see some enthusiasm!\r
OK! It's time for the\nActing Competition!\rShow off the moves that\nexemplify toughness!\rFour performances each!\nLet's see some enthusiasm!\r
OK! It's time for the\nActing Competition!\rShow off the moves that\nexemplify beauty!\rFour performances each!\nLet's see some enthusiasm!\r
OK! It's time for the\nActing Competition!\rShow off the moves that\nexemplify coolness!\rFour performances each!\nLet's see some enthusiasm!\r
COOL CONTEST
BEAUTY CONTEST
CUTE CONTEST
SMART CONTEST
TOUGH CONTEST
NORMAL RANK
GREAT RANK
ULTRA RANK
MASTER RANK
PRACTICE
LINK
CONTEST
EXIT
    
    
    
    
    
    
    
    
    
    
    
    
    
    
In the next turn, the\nlowest-scoring contestants\fwill perform first.\r
That's it! Performance\njudging is now over!\r
                                                                                     
Looks like everyone's here!\rLet's begin our practice\nActing Competition!\rFirst, choose the move your\nPokémon will perform.\rNext, choose the Judge\nwho you would like to\frate the performance.\rEach contestant gets to\nperform four times.\rGet your Pokémon to leave\na stronger impression on\rthe Judge, and score more\nhearts than the others!\rWell, here's to great\nperformances by all!\r
Communicating.\nPlease standby...