num: 51
seed: 0x5ef3
Dr. Footstep: Pokémon are quite easy\nfor me to read.\rI need only to see their footprints,\nand their innermost thoughts are\frevealed to me!\rOh?\nYou are skeptical of my claim?\rThen, let your \v0100\x0000 walk\nin front of me, right here.\rFrom its footprints, I will determine\nhow it feels about you.\r
Dr. Footstep: Do you want to check\nthe feelings of your Pokémon again?\rThen, let your \v0100\x0000 walk\nin front of me, right here.\rFrom its footprints, I will determine\nhow it feels about you.\r
Dr. Footstep: ...And that is what\nyour \v0100\x0000 thinks of you.
Dr. Footstep: ...Hmmm... \v0100\x0000\ndoesn't leave any footprints.\rIt's somewhat difficult for me to\ndetermine what its thoughts are.
Dr. Footstep: ...Hmm... \v0100\x0000\nhappens to be quite the silent type!
Dr. Footstep: ...And that is what\nyour \v0100\x0000 thinks of you.\rI must say, your \v0100\x0000 and\nyou share a very close bond.\fThis is for you.\r
Dr. Footstep: ...Hmmm... \v0100\x0000\ndoesn't leave any footprints.\rIt's somewhat difficult for me to\ndetermine what its thoughts are.\rHowever, your \v0100\x0000 and\nyou obviously share a close bond.\fThis is for you.\r
Dr. Footstep: ...Hmm... \v0100\x0000\nhappens to be quite the silent type!\rHowever, your \v0100\x0000 and\nyou obviously share a close bond.\fThis is for you.\r
\v0103\x0001 received\nthe Footprint Ribbon.\r
\v0103\x0001 put the Footprint Ribbon\non \v0100\x0000.
Aww... \v0103\x0001 only plays with\nother Pokémon...\r\v0101\x0002 feels neglected...\rMaybe \v0103\x0001 doesn't like\n\v0101\x0002 very much?\r\v0101\x0002 will try harder for\n\v0103\x0001.\rPlease be nicer to me!\r
Others say there are people who\naren't very nice to Pokémon.\rI wonder about \v0103\x0001...\rWill \v0103\x0001 look after\n\v0101\x0002 nicely?\rWill I get to go all over with this\nTrainer?\rCan we be... Friends?\r
This adventure with \v0103\x0001\nis lots of fun.\r\v0101\x0002 gets to go places where\nI can't go by myself.\rI get to battle Pokémon I've never\never seen before.\rI'm gonna get stronger and stronger\nfor \v0103\x0001!\r
\v0101\x0002 and \v0103\x0001 make\na perfectly matched combo!\rI've seen all sorts of people\nso far...\rBut \v0103\x0001 understands\n\v0101\x0002's feelings most!\rI'm a little hungry...\nYou can tell, right?\r
If I said there can be friendship\nbetween Pokémon and people, will\f\v0100\x0000's friends understand?\rBut if you see \v0103\x0001 and\n\v0101\x0002, you will understand.\rBecause \v0103\x0001 and\n\v0101\x0002 are friends!\r
\v0101\x0002 is bored...\nPlay with me more, more...\r\v0101\x0002 and \v0103\x0001,\nlet's play nicer...\r
Gonna go with \v0103\x0001 all over\nthe place...\rBe nice to \v0101\x0002...\nWarm and cuddly...\r
\v0101\x0002 get strong, make\n\v0103\x0001 happy.\rRound ones, square ones,\ntriangle ones, wobbly ones...\r\v0101\x0002 wants to see different\nkinds of Pokémon...\r
\v0101\x0002 and \v0103\x0001\nmake a friendly combo.\r\v0103\x0001's feelings, \v0101\x0002\ncan understand.\r\v0101\x0002's feelings, \v0103\x0001\nunderstands!\r
\v0103\x0001 makes \v0101\x0002\nvery proud!\r\v0100\x0000 boasts to friends\nabout \v0103\x0001!\r\v0103\x0001 and \v0101\x0002 are\nbest of friends!\r
Why does \v0103\x0001 use only\nother Pokémon?\rAm I not needed much?\rWould I have been better off if\nI remained in the wild?\rNo, I should give this Trainer\na little more of a chance...\r
Humans can't understand the cries\nof Pokémon, nor our feelings.\rHowever, there are some among us\nthat understand human speech...\rHehehe, \v0103\x0001, you're not bad\nfor a human.\r
If a Pokémon were to travel along,\nit would be limited as to where\fit could go.\rBut traveling with a human, a Pokémon\nwould be able to travel farther afield\fto more distant cities and lands.\rTraveling with \v0103\x0001 has been\nrewarding and reassuring.\rAnd very entertaining...\r
Some wild Pokémon frown upon others\nfor traveling with humans.\rThey jeer that the caught Pokémon\nhave “forgotten the wild.”\rBut that view is mistaken.\rThey have just never met a Trainer\nwho could be a great partner.\rA great partner like \v0103\x0001,\nin other words...\r
\v0103\x0001 is...\nA remarkable human and Trainer.\rThat I can always perform the best\nany \v0100\x0000 possibly can...\rI attribute that entirely to my\npartner \v0103\x0001.\rWhen we travel, I can see wild\nPokémon eyeing us enviously...\r
Does \v0103\x0001 intend to ignore\nme forever?\rGive me more opportunities for me\nto shine...\r
If a Pokémon is treated as a friend,\nit will return the sentiments.\rWe grow fonder of humans that treat\nus with kindness...\rDoes \v0103\x0001 even like\n\v0101\x0002?\r
Did \v0101\x0002 get stronger?\nWho is responsible for making me so?\rIs it \v0103\x0001's doing?\nIs the Trainer owed my thanks?\r
\v0103\x0001 and \v0101\x0002 are\nalike in some ways.\rIn humanspeak, we match up well.\nDoes \v0103\x0001 think so, too?\r
\v0103\x0001 is very impressive,\nespecially for a human.\rThe Trainer lets \v0101\x0002 use\nevery bit of power properly.\rIt is a shame that \v0103\x0001 is\nonly a human...\r
That \v0103\x0001...\nWhat is that Trainer thinking?\rWhy make me join the team, then call\nupon me for nothing?\rAm I considered useless?\nIs the Trainer regretting having me?\rDoes the Trainer dare disrespect\nthis \v0100\x0000 so easily?\r
I have little understanding of\n\v0103\x0001 as a human...\r\v0103\x0001 may not be too bad,\nconsidering that I, an oft-shunned\f\v0100\x0000, am one of the team...\rThat said, I don't intend to be all\ncheerful around \v0103\x0001...\r
Our kind prefers to lurk in dark\nand dank places...\rBut being with \v0103\x0001, even\nbright and festive places seem less\fthreatening...\r\v0103\x0001 has a strange\ncharisma...\r
Not for a moment did I think I would\nbe traveling with a human...\rIf my \v0100\x0000 friends were to\nsee me now, they would be shocked.\rOr would they be envious of me...?\r
That \v0103\x0001 is the most\nimpressive of humans.\rIt takes a lot to make me,\n\v0101\x0002, sunny and cheerful!\rAs a show of affection, I should\nchomp down on the Trainer's neck...\rHahaha... Have no fear...\nI was merely joking...\r
Wooooooh...\n\v0101\x0002 has nothing to do...\rKeep me too bored, and I'm liable\nto sneak up and bite...\r
Is there any human that would grow\nto like us \v0100\x0000?\rWell? Does \v0103\x0001 like\n\v0101\x0002?\r\v0101\x0002 doesn't like...\nWell, no, maybe not...\r
\v0103\x0001 treats me, \v0101\x0002,\nnicely without being scared.\rBut \v0101\x0002 will be even scarier\nfrom now on.\rThat's what we \v0100\x0000 do...\r
\v0101\x0002 is starting to forget\na little about being in the wild...\rBut \v0101\x0002 isn't feeling sad.\nIt's never boring with \v0103\x0001...\r
There are no Pokémon that dislike\nhumans...\rOnly humans that dislike Pokémon...\rWe \v0100\x0000 are especially\nshunned...\rBut \v0103\x0001 always treats me\nas a friend and partner...\r
Hnurrrr... Hunh?\nThis is... Where?\r\v0103\x0001's house, is this?\nIt's not? Hnurrr...\rIf you don't need me for anything,\ncan I go back to my Ball?\rHnurrr...\r
Hnurrr... Me? Uhm...\nI like to sleep most the time.\fOh, I like to eat, too. That's next.\rBut what I really like is to think.\nI'm a very deep thinker.\rWhen I think about the future of the\n\v0100\x0000 species...\r...Hnurrr...hunh?\nOh, I forget where the time goes.\rHnurrrr...\r
Hnurrr... Me? Uhm...\nThere are lots of kinds of moves.\rI like those Dark-type moves,\noh, and Dragon-type moves, too...\rHow would they be for this\n\v0100\x0000?\rWill they be for me?\nOr a no, no, no sort of thing?\rHnurrr...\r
Hnurrr... I don't know how to begin\nsaying this...\rI liked living quietly before I met\n\v0103\x0001. Sssh.\rBut I'm getting to like traveling\nwith \v0103\x0001.\rI think I'm getting sort of funky.\nDo you think I'm sort of funky?\rNo? No funk for me?\nHnurrr...\r
Hnurrr... Me? Uhm...\nOther Pokémon, they say to me...\r“You're not thinking, are you?”\nHow insulting they should say so.\rIt isn't true what they say.\nThink, think, think, I do that.\rAll the time, I think hard how to help\n\v0103\x0001. I concentrate!\rHnurrr...\r
Hnurrr... I did not know that?\nI really don't? What is this?\fI don't know what to say?\fHnurrr...\r
Hnurrr... Well, I...\nI think I'm motivated.\fAs motivated as the average.\fBut it's not so simple as that.\fHnurrr...\r
Hnurrr... How should I say this?\nWe both look out for each other.\fThat's what we try to do, I think.\fThat is for the best.\fHnurrrr...\r
Hnurrr... How do I say?\nHow should I describe us?\rWe are the sound of both hands\nclapping.\r\v0103\x0001 and I are together\nin synchronicity like twins.\rHnurrr...\r
Hnurrr...\nWhat is left to say, I say?\rWe have come so far now, where can\nwe go but to see this through?\rHall of Fame...\nWords so sweet fall from my mouth.\rHnurrr...\r
Sssshhnnn...\n...\f...Ssshhhnnn...\f...\fSsshhhnnn...\f...\r