num: 3
seed: 0xd423
\v0103\x0000: Darn it!\nWhat was that all about?!\rOh, hey, \v0103\x0001.\nThat Buck guy wiped us!\rOh, man... There's always tough\nTrainers around everywhere.\rBut you know? Losing means I have\nroom to become even tougher.\rThat's why there's the Battle Tower\nin the Battle Zone.
\v0103\x0000: Darn it!\nI'm still choked up from losing.\rBut you know? Losing means I have\nroom to become even tougher.\rThat's why there's the Battle Tower\nin the Battle Zone.
\v0103\x0000: Hey, \v0103\x0001!\nAre you still raising your Pokémon?\rMe? You need to ask? Of course I am.\nThey're my partners!\rI'm going to rule at the Battle Tower\nwith them.\rI'll prove how strong we've become\nand totally shock the guy there.