num: 26
seed: 0xd0
DECOR
DECORATE
PUT AWAY
MOVE GOODS
CANCEL
Pick decoration goods stored on the\nPC and display them.
Take goods displayed in your Secret\nBase and put them away in your PC.
Move displayed decoration goods inside\nyour Secret Base.
Cancel decorating.
Goods Set
\v0133\x0000/\v0133\x0001
The \v010a\x0000 was placed.
It can't be placed here.
The \v010a\x0000 was\nreturned to the PC.
The Big Boulder was removed.
You can't remove a Big Boulder.
You can't move a Big Boulder.
You are able to remove \v0133\x0000 more\nBig Boulder.
No more Big Boulders can be removed.
There are no decoration goods stored\non your PC.
No more decoration goods can be\ndisplayed.
That decoration good is already out\non display.
The PC cannot be put away.
The PC cannot be moved.
Quit decorating.
You are able to remove \v0133\x0000 more\nBig Boulders.