num: 19
seed: 0xee93
Your quest for power has brought\nyou here...\r...Very well.\rLet me reward your passion with some\nabsolutely astounding moves.\rThey're the ultimate moves!\nShall I teach them to your Pokémon?
The ultimate moves!\nShall I teach them to your Pokémon?
To which Pokémon should I teach\na move?\r
Hmm... Well, that is fine, as well.\nVisit if you have a change of heart.
To which Pokémon should I teach\na move?
That Pokémon can't learn a move!\nRead the poster! Keh!
Teach a move to an Egg?\nImpossible even for me! Keh!
You've not bonded strongly enough\nwith your Pokémon! Keh!
That Pokémon already knows the move\nI've offered to teach! Keh!
I should teach Blast Burn to\nyour \v0100\x0000?
I should teach Hydro Cannon to\nyour \v0100\x0000?
I should teach Frenzy Plant to\nyour \v0100\x0000?
\v0100\x0000 learned\n\v0106\x0001!
\v0100\x0000 is trying to learn\n\v0106\x0001.\rBut \v0100\x0000 can't learn more\nthan four moves.\rDelete an older move to make\nroom for \v0106\x0001?
Is it OK to forget the\nmove \v0106\x0001?
1, 2, and... ... ... Poof!\r\v0100\x0000 forgot how to\nuse \v0106\x0001.\rAnd...\n\v0100\x0000 learned \v0106\x0002.
Stop trying to teach \v0106\x0001?
\v0100\x0000 did not learn\nthe move \v0106\x0001.
To the Pokémon listed here,\nthe ultimate moves may be taught!\rThe blazing fire Pokémon\n\v0203\x0007CHARIZARD TYPHLOSION\f\v0203\x0007BLAZIKEN INFERNAPE\rThe restless water Pokémon\n\v0203\x0007BLASTOISE FERALIGATR\f\v0203\x0007SWAMPERT EMPOLEON\rThe quiet grass Pokémon\n\v0203\x0007VENUSAUR MEGANIUM\f\v0203\x0007SCEPTILE TORTERRA