num: 28
seed: 0x49b7
Dawn: Hey, \v0103\x0000?\nThe professor told me something.\rHe thinks \v0100\x0001 may have\nreappeared at the Spear Pillar...
Dawn: Hi, \v0103\x0000!\rYou're friends with the elder of\nCelestic Town, aren't you?\rShe told me that she had something\nshe wanted to show you.
Dawn: Hi, \v0103\x0000!\nMay I see your Pokédex?\r...\rOh, my gosh! You've seen every kind\nof Pokémon in Sinnoh!\rHave you shown your Pokédex to\nProf. Rowan yet?
Dawn: Hey, \v0103\x0000, have you\never chatted with my kid sister?
Dawn: Oh, \v0103\x0000, are you\nacquainted with Bebe?\rShe lives in Hearthome City.\rEvery Trainer should make it a point\nto pay Bebe a visit.
Dawn: Hey! \v0103\x0000, you've got\na Poké Radar?\rWatch for tall grass to rustle wildly\nwhen you use your Poké Radar.\rThat could be a sign that a rare\nPokémon is hiding in there.
Dawn: Hi, \v0103\x0000!\nHow's your Poké Radar?\rWhen you use it, do you sometimes\nsee more than one patch of tall\fgrass rustling?\rThe patch farther away gives you a\nbetter chance of seeing the same\fkind of Pokémon in a row.\rThat's the feeling I get, anyways.
Dawn: Sometimes a patch of grass\nsparkles when a Poké Radar is used.\rPeople say a different-colored\nPokémon is hiding there!\rCould that be true?
Dawn: So, \v0103\x0000.\rI'm also helping the professor put\ntogether the National Pokédex.\rCatching Pokémon can be really\nchallenging, can't it?\rBut, it's also so much fun!
Dawn: \v0103\x0000!\r\v0103\x0000, \v0103\x0000,\n\v0103\x0000!\rCongratulations for completing\nthe National Pokédex!
Dawn: Is today maybe...\nYour birthday, \v0103\x0000?
Dawn: Giggle...\nCongratulations, \v0103\x0000!\fAnd many more happy returns!
Dawn: Oh, it isn't?\rI wonder what made me think that\ntoday was your birthday?
Dawn: \v0103\x0000!\nI heard from the professor!\rCongratulations, Champ!
Lucas: Hey, \v0103\x0000!\nThe prof told me something cool.\rHe thinks \v0100\x0001 has\nreappeared at the Spear Pillar!
Lucas: Hi, \v0103\x0000!\rYou know the elder of Celestic Town,\nright?\rShe told me she wanted to show you\nsomething.
Lucas: Hey, \v0103\x0000!\nLet me take a look at your Pokédex.\r...\rAwesome! You've seen every kind\nof Pokémon in Sinnoh!\rHave you shown this Pokédex to\nProf. Rowan yet?
Lucas: Hey, \v0103\x0000, have you\never seen my kid sister?
Lucas: Hey, \v0103\x0000, have you\nmet Bebe?\rShe lives out in Hearthome City.\rIf you're a Trainer, you owe it to\nyourself to visit her.
Lucas: Hey! \v0103\x0000, you've got\nyourself a Poké Radar, too?\rWatch for tall grass to rustle wildly\nwhen you use that Poké Radar.\rThat's a sign that rare Pokémon\nmay be hiding there.
Lucas: Hi, \v0103\x0000!\nHow's your Poké Radar working out?\rWhen you use it, do you sometimes\nsee more than one patch of tall\fgrass rustling?\rThe patch farther away gives you a\nbetter chance of seeing the same\fkind of Pokémon right in a row.\rI think that's how it goes.
Lucas: Sometimes a patch of grass\nsparkles when a Poké Radar is used.\rThey say a different-colored\nPokémon is hiding there!\rI wonder if that's true?
Lucas: So, \v0103\x0000.\rI'm also helping the professor out\nwith the National Pokédex.\rCatching Pokémon can be really\nchallenging, can't it?\rBut I also have a ton of fun doing it!
Lucas: \v0103\x0000!\rWow! I don't know what to say!\nI mean, it's so awesome and all...\rSincerely, congratulations for\ncompleting the National Pokédex!
Lucas: Hey, \v0103\x0000?\nIs it maybe your birthday today?
Lucas: I thought so!\nCongratulations, \v0103\x0000!\fYou know, I'm glad we're friends!
Lucas: Huh?\nIt isn't?\rNow, what made me think it was\nyour birthday? Freaky weird.
Lucas: \v0103\x0000!\nThe professor told me the news!\rCongratulations, Champ!