num: 23
seed: 0x8e95
Hi!\nHow's it going?\rYou're in the \v013d\x0001 group with\n\v0103\x0000 as leader, right?\rWould you like to leave that group\nand join another one?
Hi!\nHow's it going?\rYou're in the \v013d\x0001 group with\n\v0103\x0000 as leader, right?\rWould you like to leave that group\nand make a new one?
Hi, I know it's a little sudden, but\nwould you like to join a group?\rIf you join a group, you can compete\nor cooperate with fellow members.\rIt's a lot of fun.\nWant to join?\r
Which group would you like to join?
Oh.\nThat's too bad.
Oh, you want to make a new group?\nSure thing!\rThe group you made before will be\ndisbanded, though. Is that OK?
Yay, cool! What do you want to name\nyour group?
The \v013d\x0000 group, huh?\nThat's a great name!\rThe leader is \v0103\x0001.\nI hope the group gets more members.
The \v013d\x0000 group?\n\v0103\x0001 is the leader.\fWould you like to join this group?
OK! \v0103\x0000 is now a member\nof the \v013d\x0001 group.
When you form or join a new group,\nbe sure to visit any Union Room.\rMix your records with group members,\nand you'll become integrated.\rWhen you're in the same group,\nevents can happen simultaneously.\rIt makes things a lot more fun\nplaying in a group!\rAnyone can make a group, and anyone\ncan join.\rI hope you recruit lots of friends\nso everyone can have fun!
MAKE GROUP
JOIN GROUP
INFO
EXIT
\v013d\x0000 Group
\v013d\x0001 Group
\v013d\x0002 Group
\v013d\x0003 Group
\v013d\x0004 Group
EXIT
That group?\nDidn't \v0103\x0000 make it already?
Isn't there already another group\nwith that name?