num: 80
seed: 0x3d5b
                 
Logging on to Nintendo WFC.\nPlease wait...
\v0103\x0000 is seeking someone\nto battle.
\v0103\x0000 is seeking someone\nto trade with.
\v0103\x0000 is on standby.
What would you like to seek?
Suspend your invitation?
\v0103\x0000 contacted you!
Would you like to log out of\nNintendo WFC?
                            
\v0103\x0000 invites you for\na voice chat!
\v0103\x0000 appears to be busy...
You can't connect with\n\v0103\x0000.
Communicating with \v0103\x0000...
\v0103\x0000 failed to respond...
\v0103\x0000 ended the voice chat.
Would you like to end\nthis voice chat?
Nintendo Wi-Fi Connection
Connected Friends
  
   
         
          
IN BATTLE
TRADE
TRADING...
VOICE CHAT
INVITE
              
APPLY
RECORDS
CANCEL
\v0103\x0000
GROUP
BATTLE RECORD
WIN: \v0135\x0000
LOSE: \v0135\x0000
POKéMON TRADES
\v0135\x0000 time
DATE LAST PLAYED
\v014a\x0001 \v0133\x0002, \v0135\x0000
This is your record with\n\v0103\x0000.
\v0103\x0000 wants to play with you!
Would you like to have another\nbattle against \v0103\x0000?
Would you like to do another\ntrade with \v0103\x0000?
Standing by...
DISCONNECT
\v0103\x0000 is in a battle.
\v0103\x0000 is trading.
\v0103\x0000 is having\na voice chat.
                              
Reconnect to Nintendo WFC?
You need at least two Pokémon\nif you want to trade!
Voice chat was turned ON.\r
Voice chat was turned OFF.\r
???
SINGLE BATTLE
DOUBLE BATTLE
FREE SINGLE
LV. 50 SINGLE
LV. 100 SINGLE
FREE DOUBLE
LV. 50 DOUBLE
LV. 100 DOUBLE
Your friend ended the communication\nbattle.
Communicating. Please standby...
You can't have a Double Battle\nif you only have one Pokémon...
Suspend your response?
Voice chat will be turned ON while\nyou play with this friend.\rWould you like to respond to this\nfriend's invitation?
Voice chat will be turned OFF while\nyou play with this friend.\rWould you like to respond to this\nfriend's invitation?
                 
                                
Waiting for the other player to\ndecide. Please wait...
                              
                             
                      
Delay will be turned ON.\r
Delay OFF = Standard mode\r
\v0103\x0000
\v0135\x0000 times