num: 20
seed: 0x4406
...Sniff...\nI do apologize.\rThis is an exclusive establishment\nopen only to a select few.\rYou might consider it a special stage\nfor the cream of the crop.\rIf you wish to enter, I suggest you\nstart by collecting lots of Ribbons.\r
...Sniff...\nI do apologize.\rThis is an exclusive establishment\nopen only to a select few.\rYou might consider it a special stage\nfor the cream of the crop.\rIf you wish to enter, I suggest you\nstart by collecting lots of Ribbons...\r...Wait! Oh, my gosh!\nLook at all your Ribbons!\rI truly apologize for my rudeness.\nIt's so out of character for me!\rIf you would be so kind, we would\nbe honored to invite you...\rOh, no, no! You really must join us\nas a full-fledged member!\r\v0103\x0000 was made a member\nwithout any say in the decision!\r
Welcome! We've looked forward to\nseeing you, \v0103\x0000.\rI do hope you will enjoy the luxurious\natmosphere and services that only\fwe can provide.
Welcome.\rMay I interest you in top-grade\nRibbons we had specially imported?\rThese Ribbons are available only\nthrough us.\r\v0103\x0000, would you like one\nfor a Pokémon, perhaps?\rRight now, I can offer you\nthe Gorgeous Ribbon.\rFor a mere $10,000, you can be the\nproud owner of one.
Welcome.\rMay I interest you in top-grade\nRibbons we had specially imported?\rThese Ribbons are available only\nthrough us.\r\v0103\x0000, would you like one\nfor a Pokémon, perhaps?\rRight now, I can offer you\nthe Royal Ribbon.\rFor a mere $100,000, you can be\nthe proud owner of one.
Welcome.\rMay I interest you in top-grade\nRibbons we had specially imported?\rThese Ribbons are available only\nthrough us.\r\v0103\x0000, would you like one\nfor a Pokémon, perhaps?\rRight now, I can offer you\nthe Gorgeous Royal Ribbon.\rFor a mere $999,999, you can be\nthe proud owner of one.
Welcome...\nOoh! That's a Gorgeous Royal Ribbon!\r\v0103\x0000, your \v0100\x0002\ncertainly looks gorgeous and royal!
\v0103\x0000 bought\na Gorgeous Ribbon.\r
\v0103\x0000 put the Gorgeous Ribbon\non \v0100\x0002.
\v0103\x0000 bought\na Royal Ribbon.\r
\v0103\x0000 put the Royal Ribbon\non \v0100\x0002.
\v0103\x0000 bought\na Gorgeous Royal Ribbon.\r
\v0103\x0000 put the Gorgeous Royal\nRibbon on \v0100\x0002.
Oh, please, \v0103\x0000.\rYou shouldn't joke about not\nhaving money.
I see.\nPlease do visit again.
Just being in here is a sign of\nstatus, just so you know.
I wish men would pay more attention\nto the way they dress themselves...
A woman worthy of being seen with\nPokémon... That's what I hope to be.
SKITTY: Skiii!
PSYDUCK: Gyaugyau!