num: 12
seed: 0xa402
Let me size you up...\rYou're going to become even tougher.\rYou'll meet many, many Pokémon.\rThat's what you should be thinking.\rEventually, the world will grow\nbigger to you!
                                                                       
                               
                                     
                          
                                                                   
               
               
                      
             
              
           