num: 31
seed: 0xa423
In Amity Square, you may go for\na stroll with a cute Pokémon.\rThe permitted Pokémon are: PIKACHU,\nCLEFAIRY, PSYDUCK, PACHIRISU,\fHAPPINY, BUNEARY, and DRIFLOON.\rPlease do come back with one!\r
In Amity Square, you may go for\na stroll with a cute Pokémon. Okey?\rThe permitted Pokémon are: PIKACHU,\nCLEFAIRY, PSYDUCK, PACHIRISU,\rHAPPINY, BUNEARY, and DRIFLOON,\nJIGGLYPUFF, TORCHIC, SKITTY,\fand SHROOMISH.\rPlease do come back with one!\nOkey?\r
In Amity Square, you may go for\na stroll with a cute Pokémon.\rOkey? Would you like to go for\na stroll with your \v0101\x0000?
Please do enjoy your time together,\njust the two of you! Okey?\r
Oh, okey? Then you would rather go\nfor a stroll with your \v0101\x0000?
I see. Please come back if you happen\nto have a change of heart. Okey?\r
Are you feeling refreshed?\nPlease come again! Okey?\r
Your \v0101\x0000 looks quite pleased\nfollowing you around.\rIt really is adorable!
Okey? The owner of Amity Square?\rI'm sure the owner is somewhere on\nthe grounds.\rSeeing Trainers with their Pokémon\nmakes our owner happy.
You may find useful items on the ground.\rThey're quite small, however.\nYour Pokémon may find them.\rYou should try talking to your\nPokémon every so often. Okey?
Are you enjoying your stroll?\rYou should try talking to your\nPokémon. It will be happy you did.
It makes me happy seeing all the\ncute Pokémon and their kind\fTrainers.
You may spend all the time you\nlike in Amity Square. Okey?
\v0101\x0000 is happily keeping up.
\v0101\x0000 appears to be very\nhappy.
\v0101\x0000 appears to be feeling\ngood.
\v0101\x0000 is looking endearingly\nat you.
\v0101\x0000 is picking at the ground\nfor some reason...
\v0101\x0000 almost tripped!
\v0101\x0000 is skipping happily.
\v0101\x0000 seems to be so happy\nit can't keep still.
\v0101\x0000 seems to be enjoying\nthe walk.
Oh?\n\v0101\x0000 is holding something!\r
Those are ruins from a time long,\nlong ago.
DRIFLOON: Foon!
I come here with my HAPPINY\nevery single day!\rI can let it run free without any\nworries at all.
HAPPINY appears to be drowsy.
Ooh, I just can't believe it!\nI'm so overjoyed with my PIKACHU!\rWherever I go, my PIKACHU follows\nme without hesitation!\rAhaha! It's just the two of us!\nWoohoo!
PIKACHU: Pikka pika!
You should talk to your Pokémon.\nIt can occasionally find things.
There is something shiny in CLEFAIRY's\nhands...