num: 116
seed: 0xbce
\vff00\x0001Status\vff00\x0000
\vff00\x0001VS demo\vff00\x0000
\vff00\x0001Move Tutor\vff00\x0000
\vff00\x0001Journal\vff00\x0000
Sleep
Touch screen
msg location
Test screen
Script
Map
Pokétch
Shop
Berry Max
TM & HM Max
F Note ADD
Field
Move Tutor
Move Deleter
Poffin
Condition
Multi 1
Start 1
End 1
Multi 2
Start 2
End 2
End 3
Move Tutor
Move Remainder
Set Ribbons
Pokémon icon
Item icon
F Note Clear
ｘ
\v0108\x0000
\v0134\x0000
Class
Level
Exp. Points
ID
Random value
Gender
Nature
Move 1
Move 2
Move 3
Move 4
Held item
Special ability
HP rnd
HP exp
Attack rnd
Attack exp
Defense rnd
Defense exp
Speed rnd
Speed exp
Sp. Atk rnd
Sp. Atk exp
Sp. Def rnd
Sp. Def exp
Coolness
Beauty
Cuteness
Smartness
Toughness
Luster
Tameness
POKéRUS
Egg
Status
HP
Attack
Defense
Speed
Special Attack
Special Defense
Event distribution
Captured place
Captured level
Captured cassette
Captured Ball
Country code
Form No.
Nickname flag
Normal
Sleep
Poison
Burned
Frozen
Paralysed
Badly poisoned
None
㊚
㊛
-
ON
OFF
\v013b\x0000
\v0100\x0000
\v0106\x0000
\v0108\x0000
\v0105\x0000
\v0107\x0000
Added a Pokémon to your party.
Added a Pokémon to the Box.
Create Pokémon\n  LR: Switch   START: Add
ＤＢＰｏｋｅ1
Egg
(Test message)\nPokémon used a move!
Diamond
Pearl
Emerald
Sapphire
\v0100\x0000
\v0108\x0000