num: 149
seed: 0xd561
          
                             
\v0101\x0000 was not traded.\r
\v0101\x0000 appears to have\nfled...\r
Are you seeking or offering a Pokémon?
Do what with this \v0101\x0000?
Will you take this \v0101\x0000?
Is it OK to disconnect from\nNintendo Wi-Fi Connection?
What kind of Pokémon are you seeking?
Please choose the Pokémon you want.
Please choose its gender.
Please choose the level.
Please choose the Pokémon you want!
Searching for the Pokémon you want...
None were found!
Stop searching?
Trade for this Pokémon?
Choose the Pokémon you are trading.
Do what with this \v0101\x0000?
                 
                 
Choose the Pokémon you want to offer.
Offer \v0101\x0000?
Are these conditions OK?
Checking GTS's status...
The Ball Capsule will be detached.\nIs that OK?
That Pokémon may not be offered\nfor trade!\r
An Egg may not be offered\nfor trade!\r
Your party is full.\nYou can't receive a Pokémon!\r
Your Storage Boxes are full.\nYou can't receive a Pokémon!\r
A trade partner has been found!
Nintendo Wi-Fi Connection
Touch to select your trade partner.
Please change your conditions.
Please wait a while.
Your party is full.\rYou can't receive a Pokémon that\nis holding Mail.\r
There is no room in your party.
It has a special Ribbon.\nIt can't be offered for a trade.\r
GTS check failed.
GLOBAL TRADE SYSTEM
SUMMARY
SEEK POKéMON
EXIT
\v0101\x0000
\v0100\x0001
Lv. \v0134\x0002
ITEM
\v0108\x0003
OFFERER
\v0103\x0004
POKéMON WANTED
\v0100\x0005
Lv. \v0134\x0006 and up
Any level
TAKE BACK
LEAVE AS IS
Yes
No
SEARCH FOR POKéMON
POKéMON
\v0100\x0000
GENDER
\v0128\x0000\x0001
LEVEL
\v0129\x0000\x0002
SEARCH
BACK
    
    
       
ITEM
    
      
    
WANTED
    
     
     
OT'S LOCATION
\v0124\x0008
\v0125\x0009
        
   
    
SUMMARY
TRADE
CANCEL
Yes
No
IN PARTY
DEPOSIT POKéMON
    
        
   
SUMMARY
OFFER
CANCEL
WANTED
    
     
OFFER POKéMON
    
Lv. \v0134\x0003
CANCEL
ABC
DEF
GHI
JKL
MNO
PQR
STU
VWX
YZ
 
EITHER
♂
♀
CANCEL
ANY
Lv. 9 and under
Lv. 10 and up
Lv. 20 and up
Lv. 30 and up
Lv. 40 and up
Lv. 50 and up
Lv. 60 and up
Lv. 70 and up
Lv. 80 and up
Lv. 90 and up
LV. 100
CANCEL
                     
                      
                     
                     
                      
                       
Unfortunately, it was traded to\nanother Trainer.\r
Saving...\nDo not turn off the power.
                          
The GTS is currently\nundergoing maintenance.\rPlease try again later.\r
The GTS is very crowded now.\nPlease try again later.\r
The search failed...
Communication error...
Communication error...\r
Unable to connect to the GTS.\nReturning to the reception counter.\r
You were disconnected from the GTS.\nReturning to the reception counter.\r
You were disconnected from the GTS.
Returning to the reception counter.