num: 216
seed: 0xaa22
\vff00\x0001Pokémon Diamond\vff00\x0000
\vff00\x0001Pokémon Pearl\vff00\x0000
\vff00\x0001Credits\vff00\x0000
\vff00\x0002Director\vff00\x0000
    Junichi Masuda
\vff00\x0002Art Director\vff00\x0000
    Ken Sugimori
\vff00\x0002Battle Director\vff00\x0000
    Shigeki Morimoto
\vff00\x0002Program Leader\vff00\x0000
    Tetsuya Watanabe
\vff00\x0002Battle System Programmer\vff00\x0000
    Hisashi Sogabe
\vff00\x0002Field System Programmer\vff00\x0000
    Sousuke Tamada
\vff00\x0002Communication System Programmer\vff00\x0000
    Akito Mori
\vff00\x0002Programmers\vff00\x0000
    Yoshinori Matsuda
    Keita Kagaya
    Hiroyuki Nakamura
    Masao Taya
    Satoshi Nohara
    Tomomichi Ohta
    Miyuki Iwasawa
    Nozomu Saito
    Daisuke Goto
    Tomoya Takahashi
    Katsumi Ono
    Satoshi Mitsuhara
\vff00\x0002Graphic Leader\vff00\x0000
    Takao Unno
\vff00\x0002Pokémon Designers\vff00\x0000
\vff00\x0002\v0203\x0056&\vff00\x0000
\vff00\x0002\v0203\x003aGraphic Designers\vff00\x0000
    Ken Sugimori
    Takao Unno
    Motofumi Fujiwara
    Satoshi Ohta
    Hironobu Yoshida
    Kanako Eo
    Kenkichi Toyama
    Hiroki Fuchino
    Hiroyuki Yagi
    Emi Yoshida
    Yusuke Omura
    Hiroyuki Goto
\vff00\x0002Pokémon Designer\vff00\x0000
    Atsuko Nishida
\vff00\x0002Graphic Designer\vff00\x0000
    Kei Hoshiba
\vff00\x0002Music Leader\vff00\x0000
    Go Ichinose
\vff00\x0002Music Composition\vff00\x0000
    Hitomi Sato
    Junichi Masuda
\vff00\x0002Sound Effects\vff00\x0000
    Satoshi Nohara
\vff00\x0002Pokémon Voices\vff00\x0000
    Go Ichinose
\vff00\x0002Game Design Leader\vff00\x0000
    Shigeru Ohmori
\vff00\x0002Game Designers\vff00\x0000
    Kouji Nishino
    Kenji Matsushima
    Tetsuji Ohta
    Hitomi Sato
    Takeshi Kawachimaru
    Teruyuki Shimoyamada
    Tadashi Takahashi
    Akihito Tomisawa
    Suguru Nakatsui
    Hiro Nakamura
\vff00\x0002Plot Scenario\vff00\x0000
    Junichi Masuda
    Toshinobu Matsumiya
    Kouji Nishino
    Shigeru Ohmori
\vff00\x0002Game Scenario\vff00\x0000
    Toshinobu Matsumiya
    Hitomi Sato
    Akihito Tomisawa
    Suguru Nakatsui
\vff00\x0002Map Designers\vff00\x0000
    Tadashi Takahashi
    Suguru Nakatsui
    Shigeru Ohmori
    Akihito Tomisawa
    Hiro Nakamura
    Kouji Nishino
    Teruyuki Shimoyamada
\vff00\x0002Pokédex Text\vff00\x0000
    Kenji Matsushima
\vff00\x0002Parametric Designers\vff00\x0000
    Kouji Nishino
    Tetsuji Ohta
    Teruyuki Shimoyamada
    Shigeki Morimoto
\vff00\x0002Battle Tower Data\vff00\x0000
    Osamu Fujita
    Takeshi Saigo
    Yoshihito Tsuji
    Kouji Kobayashi
    Motoki Nakajima
    Etsuko Fukushima
    Keisuke Fukushima
    Tetsuji Ohta
\vff00\x0002Script Designers\vff00\x0000
    Satoshi Nohara
    Tomomichi Ohta
    Miyuki Iwasawa
    Sousuke Tamada
\vff00\x0002Environment & Tool Programmers\vff00\x0000
    Hisashi Sogabe
    Sousuke Tamada
    Hiroyuki Nakamura
    Masao Taya
    Miyuki Iwasawa
\vff00\x0002Nintendo Wi-Fi Connection\vff00\x0000
  \vff00\x0002Server System Director\vff00\x0000
    Mikihiro Ishikawa
  \vff00\x0002Server System Programmers\vff00\x0000
    Daisuke Nakamura
    Shigetoshi Kitayama
    Yuuki Hayashi
  \vff00\x0002Program Support\vff00\x0000
    Kazuki Yoshihara
\vff00\x0002NCL Product Testing\vff00\x0000
    Akira Yano
    Super Mario Club
\vff00\x0002Special Thanks\vff00\x0000
    Kenji Tominaga
    Yoshio Tajiri
    Masafumi Saito
    Saya Tsuruta
    HyunJung Lee
    Takenori Ohta
    Teiko Sasaki
    Yuichiro Mori
    Sachiko Hamano
    Emi Endo
    Kenjiro Ito
    Tomotaka Komura
    Susumu Fukunaga
    Masami Tanaka
    Michiko Takizawa
    Kenichi Arai
    Yumi Hoshi
    Jiro Koga
    Norihide Okamura
    Shunsuke Kohori
    Takanao Kondo
    Hiroyuki Uesugi
    Teruki Murakawa
    Kimiko Nakamichi
    Souichi Yamamoto
    Akira Kinashi
    Hiroshi Akune
    Takao Nakano
\vff00\x0002Information Supervisors\vff00\x0000
    Hiromi Sagawa
    Yuri Sakurai
    Naoko Yanase
\vff00\x0002Artwork\vff00\x0000
    Sachiko Nakamichi
    Kiyomi Oe
    Yasuko Sugiyama
\vff00\x0002Coordinators\vff00\x0000
    Shusaku Egami
    Kazuki Yoshihara
    Kaori Ando
\vff00\x0002English Version Coordinators\vff00\x0000
    Seth McMahill
    Keisuke Tominaga
\vff00\x0002English Version Assistant Coordinator\vff00\x0000
    Joel Simon
\vff00\x0002Translator\vff00\x0000
    Nob Ogasawara
\vff00\x0002Text Editors\vff00\x0000
    Teresa Lillygren
    Seth McMahill
\vff00\x0002NOA Product Testing\vff00\x0000
    Thomas Hertzog
    Leland Jones
    Patrick Taylor
    Mika Kurosawa
\vff00\x0002NOA Special Thanks\vff00\x0000
    Nicola Wright
    Devon Ryning
    Hitomi Ross
    Kyle Hudson
    Joshua Newman
\vff00\x0002Localization\vff00\x0000
    Teruki Murakawa
    Kimiko Nakamichi
    Souichi Yamamoto
    Akira Kinashi
    Noriko Nakao
    Ken Kato
    Norihito Ito
    Haruhiko Imatake
    Tomoko Nakayama
    Hiroshi Akune
    Kazuhiro Fujihara
    Yuuki Tanikawa
    Ryo Yamaguchi
\vff00\x0002Producers\vff00\x0000
    Hiroyuki Jinnai
    Hitoshi Yamagami
    Gakuji Nomoto
    Hiroaki Tsuru
\vff00\x0002Executive Producers\vff00\x0000
    Satoshi Tajiri
    Satoru Iwata
    Tsunekaz Ishihara
Fin