num: 197
seed: 0xe14e
CONFIRM
CANCEL
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0101\x0000
\v0101\x0000
\v0101\x0000
\v0101\x0000
\v0101\x0000
\v0101\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
\v0134\x0000
/
♂
♀
Choose a Pokémon.
Move to where?
Give to which Pokémon?
Use on which Pokémon?
Teach which Pokémon?
Choose Pokémon and confirm.
             
Use on which Pokémon?
Do what with\n\v0101\x0000?
Do what with\nan item?
Do what with\nthe Mail?
Restore\nwhich move?
Boost the PP\nof which move?
Set this\ncustomized Ball?
Send the removed Mail to\nyour PC?
Yes
No
The Mail was sent to your PC.
If the Mail is removed, its written\nmessage will be lost. Is that OK?
Yes
No
Your PC's Mailbox is full.
Mail was taken from the\nPokémon.
\v0101\x0000 wants to learn the\nmove \v0106\x0001.\rHowever, \v0101\x0000 already\nknows four moves.\rShould a move be deleted and\nreplaced with \v0106\x0001?
Yes
No
Stop trying to teach\n\v0106\x0001?
Yes
No
\v0101\x0000 did not learn the\nmove \v0106\x0001.
Which move should be\nforgotten?
1, \v0201\x00142, and\v0201\x0014... \v0201\x0014... \v0201\x0014... Poof!\v0202\x0003\v0202\x0005\r\v0101\x0000 forgot how to\nuse \v0106\x0001.\rAnd...
\v0101\x0000 learned\n\v0106\x0001!\v0202\x0004\v0202\x0002
\v0101\x0000 and \v0106\x0001\nare not compatible.\r\v0106\x0001 can't be learned.
\v0101\x0000 already knows\n\v0106\x0001.
\v0101\x0000's HP was restored\nby \v0134\x0001 point(s).
\v0101\x0000 was cured of its\npoisoning.
\v0101\x0000 was cured of\nparalysis.
\v0101\x0000's\nburn was healed.
\v0101\x0000 was\nthawed out.
PP was restored.
\v0101\x0000\nregained health.
\v0101\x0000\nbecame healthy.
\v0106\x0000's PP\nincreased.
\v0101\x0000 snapped out of its\nconfusion.
\v0101\x0000 got over its\ninfatuation.
\v0101\x0000's base \v010d\x0001\nrose!
This can't be used until a new\nBadge is obtained.
Must remove Mail before the\nPokémon is allowed to hold an item.
\v0101\x0000 is already holding\n\v0108\x0001.\rWould you like to switch the\ntwo items?
Yes
No
\v0101\x0000 isn't holding\nanything.
Received the \v0108\x0001\nfrom \v0101\x0000.
The Bag is full.
The \v0108\x0001 was taken and\nreplaced with the \v0108\x0002.
           
  
   
             
  
   
\v0101\x0000\nwoke up.
                     
                       
  
   
                  
  
   
                
No more than two Pokémon\nmay enter.
          
You're already surfing.
             
You can't use that here.
It won't have any effect.
              
Two Pokémon are needed.
              
               
\v0101\x0000 became more friendly.\rHowever, its base \v010d\x0001 fell!
\v0101\x0000 adores you!\rIts base \v010d\x0001 fell!
\v0101\x0000 became more friendly.\rIts base \v010d\x0001 can't go lower.
\v0101\x0000 is already in battle!
\v0101\x0000 has no energy left\nto battle!
\v0101\x0000 can't be switched out!
An Egg can't battle!
You can't switch \v0103\x0000's\nPokémon with one of yours!
\v0101\x0000 was given the\n\v0108\x0001 to hold.
Three Pokémon are needed.
Four Pokémon are needed.
Five Pokémon are needed.
Six Pokémon are needed.
No more than one Pokémon\nmay enter.
No more than three Pokémon\nmay enter.
No more than four Pokémon\nmay enter.
No more than five Pokémon\nmay enter.
Mail was transferred from\nthe Mailbox.
This Pokémon is holding an item.\nIt cannot hold Mail.
The Ball Capsule was set.
Two capsules can't be set.
This can't be used on\nthat Pokémon.
                      
  
   
                    
  
   
Not enough HP...
                   
                   
                 
                  
                  
                            
SWITCH
SUMMARY
ITEM
MAIL
READ
TAKE
STORE
CANCEL
     
ENTER
NO ENTRY
\vff00\x0001\v0106\x0000\vff00\x0000
\vff00\x0001\v0106\x0000\vff00\x0000
\vff00\x0001\v0106\x0000\vff00\x0000
\vff00\x0001\v0106\x0000\vff00\x0000
GIVE
TAKE
\v0106\x0000
\v0106\x0000
\v0106\x0000
\v0106\x0000
SET
NOT ENTERED
BANNED
FIRST
SECOND
THIRD
FOURTH
FIFTH
SIXTH
ABLE!
UNABLE!
LEARNED
ABLE!
UNABLE!
ABLE!
UNABLE!
Identical Pokémon are not permitted.
Some Pokémon are holding identical\nitems.
The total of all party members'\nlevels has gone over \v0134\x0000.
MAX HP
ATTACK
DEFENSE
SP. ATK
SP. DEF
SPEED
+ \v0134\x0000
\v0134\x0000
\v0101\x0000 was elevated to\nLv. \v0134\x0001.\v0202\x0004\v0202\x0002
\v0101\x0000 learned\n\v0106\x0001!\v0202\x0004\v0202\x0002
The Ball Capsule will be detached.\nWill that be OK?
It can't be used when you have\nsomeone with you.