num: 17
seed: 0xcbaa
\vff01\x00c8Thud!!\vff01\x0064\r
What the...\r
Whoops, sorry about that!\nI was in a rush.\r
Oh, wait a second...\nAren't you...\rYou're \v0103\x0001 from Twinleaf!\nWow, that brings back memories!\rSo, if you're here, he can't be far\nbehind...\rThis should be fun.\nSee you!\r
\vff01\x00c8Thud!!\vff01\x0064\r
\v0103\x0000: What the...\rOh, hey, \v0103\x0001!\rYou came to the Battle Tower too,\nhuh?\rI decided I'll see how I measure up\nbefore going to Stark Mountain.\rBut that guy you were just talking\nto...\r...Nah, it's all right!\nI got here on my own power.\fIt won't take long before I see him.\rSee ya, \v0103\x0001!\nI'm going to toughen up here!\r
\v0103\x0000: What the...\rOh, hey, \v0103\x0001!\rYou came to the Battle Tower too,\nhuh?\rI decided I'll see how I measure up\nfor my quest to be the greatest!\rBut that guy you were just talking\nto...\r...Nah, it's all right!\nI got here on my own power.\fIt won't take long before I see him.\rSee ya, \v0103\x0001!\nI'm going to toughen up here!\r
Exchange Service Corner\nA Cornucopia of Fabulous Prizes!
Battle Tower\nGather, All Ye Greatest!
In the Battle Rooms, the seventh\nTrainer you face is the room's boss.\rYou'll need to stay focused if you\nwant to win!
If you get a big win streak at the\nBattle Tower, you get to battle\fsome real superstars.
Mwahahaha! We earned a lot of BP\nat the Battle Tower.\rNow I can exchange them for\nloads of prizes!
Aah.
I'm a babysitting Trainer!\rI'm off to the Multi Battle Rooms\nwith my beloved son!
I heard that the world's best\ngather here for battles.\rThis is my chance to get global\nfame and recognition!
The types of Pokémon!\rThe moves to be taught and used!\rThe items to be held!\rTo become number one here, there is \nno detail that can be overlooked!
I'd love to hook up with a Beauty\nfor the Multi Battle Rooms.