num: 6
seed: 0x6eb8
                 
A communication error has occurred.\n\nIf you were in the Union Room, you\nwill be returned there.\nIn all other cases, you will be\nreturned to wherever you last\nsaved.\nPlease press the A Button.
An error occurred while attempting\nto communicate. (\v0136\x0000)\nPlease turn off the power, restart\nthis DS system, and try again.\n\nIf this message keeps appearing,\nplease contact Nintendo\nConsumer Service.
A communication error has occurred.\n\nYou will be returned to the title\nscreen.\nPlease press the A Button.
The GTS is extremely busy now.\nPlease wait a while and try again.\n\nPlease press the A Button.
An error occurred while attempting\nto communicate.\nPlease turn off the power, restart\nthis DS system, and try again.\n\nIf this message keeps appearing,\nplease contact Nintendo\nConsumer Service.