num: 15
seed: 0x2462
Welcome to the Exchange Service\nCorner!\rWe can exchange your BP\nfor fabulous items.\r
Which prize would you like in\nexchange for your BP?
You've chosen the \v0108\x0000.\nIs that correct?
Here is your prize!\r
I'm so sorry...\nYou don't have enough BP...\r
Sorry, your Bag has no room for\nthis \v0108\x0000...\r
Thank you for visiting.\rPlease visit us again when you have\nsaved up BP.
You've chosen \v0108\x0000,\n\v0106\x0001. Is that correct?
What to get today...\nPerhaps a Technical Machine will do.
What I most care about is the\ncrushing power of my darling Pokémon.\rAre there any prizes that would\nhelp them get more power?
How's it going?\rIf things aren't going well, why not\ngrab some prizes here?\rIt might toughen up your Pokémon\njust enough to do better.
Gramma, Gramma!\nI went and traded!\rYou can have this, Gramma!\r
Oh, what is it, dear?\nOh, a Sludge Bomb...\rWhy, thank you so much, dear.\rYou're such a cute, tough, and kind\ngirl...\rI feel blessed to have a grandchild\nlike you...
Did you see that little girl with her\ngrandmother upstairs?\rThat girl is a little terror in battle.\nYou never can judge people!
This building is so grand...\nWhy does it need to be so?