num: 15
seed: 0x923c
Welcome to Geonet, the high-tech\nglobe!\r
What would you like to do?
Here, you may register the location\nof where you live.\rThat information may be provided to\nfriends and strangers through\rDS Wireless Communications or over\nNintendo WFC.\rWould you like to register your\nhome's location area?
Please select the location in which\nyou live.
Please select the area in which\nyou live.
Once registered, you may not change\nyour registered location data.\rShould this location be registered\nas where you live?
\v0124\x0000
\v0125\x0000
YES
NO
SEE LIST
REGISTER
EXIT
Your registered location:\n\v0124\x0000\n\v0125\x0001
To display registered locations, line up\nthe cursor, and press the X Button.