num: 92
seed: 0x27f8
You've got a Sphere or two?\nIf you do, I'll trade you something.
Which Sphere will you trade me for\nmy \v0119\x0002?
All right!\nLet's do this trade!
Oh, now wait a second!\nYou don't have any room for this!
That's not the right kind of Sphere!
Hmm...\nNo, this Sphere's not big enough.
The \v0119\x0002\nwas obtained!
You obtained a \v0119\x0002,\nsize \v0133\x0006.
Do you need anything else?
I'll be seeing you, then!
You'll trade your \v0119\x0002\nfor my \v0119\x0004?
All right!\nLet's trade!
Oh, now wait a second! You don't\nhave room for another Sphere!
GET TRAP
GIVE TRAP
EXIT
GET GOODS
GIVE GOODS
EXIT
Spheres\n on hand
Traps on\n hand
Goods on\n hand
CANCEL
Required Sphere
Offered Sphere
\v0119\x0002 \v0133\x0006
NOT FOR SALE
You have any treasures? I'll trade\nyou some Spheres for them.
GIVE TREASURES
Treasures\n on hand
                                  
                    
                                  
                               
                          
                
                                                            
                      
  
   
  
  
                               
                      
                                  
                               
                          
                
                                                    
                      
  
   
  
  
                                     
                      
                                  
                               
                          
                
                                                           
                      
  
   
  
  
                               
              
                    
                                   
                             
                                
                             
                                                    
           
           
                    
                                
                                
                                                  
              
                                           
                 
                           
                                 
                
                           
                           
                                   
                       
                                       
Roark: Hey! \v0103\x0000!\nIs this maybe your first time here?\rWelcome to Sinnoh's Underground!\rHuh? Where is this, you ask?\nDoesn't the Radar make it obvious?\rThis is a giant underground network\nof passages underneath Sinnoh.\rHuh? What am I doing down in this\nexpanse of a place?\rThat's kind of hard to answer.\rI mean, you can do pretty much\nanything you want down here.\rFor instance, you can dig up Treasure,\nSpheres, and make a Secret Base.\rYou can play with your friends down\nhere, too.\rYou should talk to the Underground\nMan in Eterna City.\rI have to get going now.\nI'll see you around!