num: 7
seed: 0x9e94
\v0103\x0000: Hey! \v0103\x0001!\nTell me you got a little tougher!\rMe? Do you even need to ask?\nOf course I got tougher!\rCome on!\nLet's battle it out!\r
\v0103\x0000: Waah!\nWhat do you mean I lost?!\rWell, that's it!\nThat's the last time I'll ever lose!\rI'm going to be the world's toughest\nTrainer, and you know it!\rThe first thing to do is take on\nthe Oreburgh City Pokémon Gym!\rI'm gonna toughen up for that,\ntotally!\r
Did you know?\rThe first Pokémon to appear in\na battle is the one at the top left\fof your team list.
Rt. 203\nJubilife City
Rt. 203\nOreburgh City
Trainer Tips!\rIf a Pokémon is about to evolve,\nit can be instantly stopped.\rPress the B Button during evolution\nto startle the Pokémon into stopping.\rThat is how evolution can be\ncanceled.
Trainer Tips!\rPokémon moves use energy called\nPower Points, or PP for short.\rIf the PP of moves runs low, head for\nany Pokémon Center.