num: 6
seed: 0xcaff
Dexter: That's it, folks!\nAll judging has been completed!\rWhich Pokémon will be crowned the\nwinner?\rLet's announce the results!\r
First, the results of the Visual\nCompetition!\r
Next, let's have the results of the\nDance Competition!\r
And finally, here are the results of\nthe Acting Competition!\r
Dexter: The winner is...\nEntry number \v0132\x0000!\r\v0103\x0001 and \v0100\x0002!\nCongratulations!\r
And now, it's time to announce the\nresults of the individual categories!\r