num: 14
seed: 0xd9ae
\v0101\x0000 has entered.
Would you like to stop drawing?
\v0101\x0000 has left.
The leader, \v0101\x0000, has left.\nThis group will be disbanded.
If the leader leaves, the group will\ndisband. Is that OK?
There are no members.\nThe group will be disbanded.
The drawing session was ended.
QUIT
\v0101\x0000
Write your autograph!
Is this OK?
Would you like to\nredo your autograph?
DONE
Joined a drawing session!